begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|jms
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|CountDownLatch
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|TimeUnit
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|atomic
operator|.
name|AtomicInteger
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|function
operator|.
name|Function
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Connection
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ConnectionConsumer
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ConnectionFactory
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ConnectionMetaData
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|DeliveryMode
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Destination
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ExceptionListener
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|InvalidClientIDException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|JMSException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Queue
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ServerSessionPool
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Session
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Topic
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|util
operator|.
name|ServiceStopper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|message
operator|.
name|Exchange
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|message
operator|.
name|ExchangeImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|message
operator|.
name|Message
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|message
operator|.
name|MessageImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|security
operator|.
name|SecurityContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|service
operator|.
name|model
operator|.
name|EndpointInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|Conduit
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|MessageObserver
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|MultiplexDestination
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|jms
operator|.
name|util
operator|.
name|ResourceCloser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Ignore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertNotNull
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertNull
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertTrue
import|;
end_import

begin_class
specifier|public
class|class
name|JMSDestinationTest
extends|extends
name|AbstractJMSTester
block|{
specifier|private
specifier|static
class|class
name|FaultyConnection
implements|implements
name|Connection
block|{
specifier|private
specifier|final
name|Connection
name|delegate
decl_stmt|;
name|FaultyConnection
parameter_list|(
specifier|final
name|Connection
name|delegate
parameter_list|)
block|{
name|this
operator|.
name|delegate
operator|=
name|delegate
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Session
name|createSession
parameter_list|(
name|boolean
name|transacted
parameter_list|,
name|int
name|acknowledgeMode
parameter_list|)
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|createSession
argument_list|(
name|transacted
argument_list|,
name|acknowledgeMode
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getClientID
parameter_list|()
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|getClientID
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setClientID
parameter_list|(
name|String
name|clientID
parameter_list|)
throws|throws
name|JMSException
block|{
name|delegate
operator|.
name|setClientID
argument_list|(
name|clientID
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|ConnectionMetaData
name|getMetaData
parameter_list|()
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|getMetaData
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|ExceptionListener
name|getExceptionListener
parameter_list|()
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|getExceptionListener
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setExceptionListener
parameter_list|(
name|ExceptionListener
name|listener
parameter_list|)
throws|throws
name|JMSException
block|{
name|delegate
operator|.
name|setExceptionListener
argument_list|(
name|listener
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|start
parameter_list|()
throws|throws
name|JMSException
block|{
name|delegate
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|stop
parameter_list|()
throws|throws
name|JMSException
block|{
name|delegate
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|close
parameter_list|()
throws|throws
name|JMSException
block|{
name|delegate
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|ConnectionConsumer
name|createConnectionConsumer
parameter_list|(
name|Destination
name|destination
parameter_list|,
name|String
name|messageSelector
parameter_list|,
name|ServerSessionPool
name|sessionPool
parameter_list|,
name|int
name|maxMessages
parameter_list|)
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|createConnectionConsumer
argument_list|(
name|destination
argument_list|,
name|messageSelector
argument_list|,
name|sessionPool
argument_list|,
name|maxMessages
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|ConnectionConsumer
name|createDurableConnectionConsumer
parameter_list|(
name|Topic
name|topic
parameter_list|,
name|String
name|subscriptionName
parameter_list|,
name|String
name|messageSelector
parameter_list|,
name|ServerSessionPool
name|sessionPool
parameter_list|,
name|int
name|maxMessages
parameter_list|)
throws|throws
name|JMSException
block|{
return|return
name|delegate
operator|.
name|createDurableConnectionConsumer
argument_list|(
name|topic
argument_list|,
name|subscriptionName
argument_list|,
name|messageSelector
argument_list|,
name|sessionPool
argument_list|,
name|maxMessages
argument_list|)
return|;
block|}
block|}
specifier|private
specifier|static
specifier|final
class|class
name|FaultyConnectionFactory
implements|implements
name|ConnectionFactory
block|{
specifier|private
specifier|final
name|ConnectionFactory
name|delegate
decl_stmt|;
specifier|private
specifier|final
name|Function
argument_list|<
name|Connection
argument_list|,
name|Connection
argument_list|>
name|wrapper
decl_stmt|;
specifier|private
specifier|final
name|AtomicInteger
name|latch
decl_stmt|;
specifier|private
name|FaultyConnectionFactory
parameter_list|(
name|ConnectionFactory
name|delegate
parameter_list|,
name|int
name|faults
parameter_list|)
block|{
name|this
argument_list|(
name|delegate
argument_list|,
name|FaultyConnection
operator|::
operator|new
argument_list|,
name|faults
argument_list|)
expr_stmt|;
block|}
specifier|private
name|FaultyConnectionFactory
parameter_list|(
name|ConnectionFactory
name|delegate
parameter_list|,
name|Function
argument_list|<
name|Connection
argument_list|,
name|Connection
argument_list|>
name|wrapper
parameter_list|,
name|int
name|faults
parameter_list|)
block|{
name|this
operator|.
name|delegate
operator|=
name|delegate
expr_stmt|;
name|this
operator|.
name|wrapper
operator|=
name|wrapper
expr_stmt|;
name|this
operator|.
name|latch
operator|=
operator|new
name|AtomicInteger
argument_list|(
name|faults
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Connection
name|createConnection
parameter_list|()
throws|throws
name|JMSException
block|{
if|if
condition|(
name|latch
operator|.
name|getAndDecrement
argument_list|()
operator|<=
literal|0
condition|)
block|{
return|return
name|wrapper
operator|.
name|apply
argument_list|(
name|delegate
operator|.
name|createConnection
argument_list|()
argument_list|)
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|JMSException
argument_list|(
literal|"createConnection() failed (simulated)"
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|Connection
name|createConnection
parameter_list|(
name|String
name|userName
parameter_list|,
name|String
name|password
parameter_list|)
throws|throws
name|JMSException
block|{
if|if
condition|(
name|latch
operator|.
name|decrementAndGet
argument_list|()
operator|<=
literal|0
condition|)
block|{
return|return
name|wrapper
operator|.
name|apply
argument_list|(
name|delegate
operator|.
name|createConnection
argument_list|(
name|userName
argument_list|,
name|password
argument_list|)
argument_list|)
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|JMSException
argument_list|(
literal|"createConnection(userName, password) failed (simulated)"
argument_list|)
throw|;
block|}
block|}
block|}
annotation|@
name|Test
specifier|public
name|void
name|testGetConfigurationFromWSDL
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldQueueBinMsgService"
argument_list|,
literal|"HelloWorldQueueBinMsgPort"
argument_list|)
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"Can't get the right AddressPolicy's Destination"
argument_list|,
literal|"test.jmstransport.binary"
argument_list|,
name|destination
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|getTargetDestination
argument_list|()
argument_list|)
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testDurableSubscriber
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
comment|// The JMSBroker (ActiveMQ 5.x) need to take some time to setup the DurableSubscriber
name|Thread
operator|.
name|sleep
argument_list|(
literal|500L
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|Message
name|destMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"The destiantion should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|verifyReceivedMessage
argument_list|(
name|destMessage
argument_list|)
expr_stmt|;
name|verifyHeaders
argument_list|(
name|destMessage
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
argument_list|(
name|expected
operator|=
name|InvalidClientIDException
operator|.
name|class
argument_list|)
specifier|public
name|void
name|testDurableInvalidClientId
parameter_list|()
throws|throws
name|Throwable
block|{
name|Connection
name|con
init|=
name|cf1
operator|.
name|createConnection
argument_list|()
decl_stmt|;
name|JMSDestination
name|destination
init|=
literal|null
decl_stmt|;
try|try
block|{
name|con
operator|.
name|setClientID
argument_list|(
literal|"testClient"
argument_list|)
expr_stmt|;
name|con
operator|.
name|start
argument_list|()
expr_stmt|;
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
name|JMSConfiguration
name|jmsConfig
init|=
name|JMSConfigFactory
operator|.
name|createFromEndpointInfo
argument_list|(
name|bus
argument_list|,
name|ei
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|jmsConfig
operator|.
name|setDurableSubscriptionClientId
argument_list|(
literal|"testClient"
argument_list|)
expr_stmt|;
name|jmsConfig
operator|.
name|setDurableSubscriptionName
argument_list|(
literal|"testsub"
argument_list|)
expr_stmt|;
name|jmsConfig
operator|.
name|setConnectionFactory
argument_list|(
name|cf
argument_list|)
expr_stmt|;
name|destination
operator|=
operator|new
name|JMSDestination
argument_list|(
name|bus
argument_list|,
name|ei
argument_list|,
name|jmsConfig
argument_list|)
expr_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|RuntimeException
name|e
parameter_list|)
block|{
throw|throw
name|e
operator|.
name|getCause
argument_list|()
throw|;
block|}
finally|finally
block|{
name|ResourceCloser
operator|.
name|close
argument_list|(
name|con
argument_list|)
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
block|}
annotation|@
name|Test
specifier|public
name|void
name|testOneWayDestination
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HWStaticReplyQBinMsgService"
argument_list|,
literal|"HWStaticReplyQBinMsgPort"
argument_list|)
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// wait for the message to be get from the destination
name|Message
name|destMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
comment|// just verify the Destination inMessage
name|assertNotNull
argument_list|(
literal|"The destiantion should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|verifyReceivedMessage
argument_list|(
name|destMessage
argument_list|)
expr_stmt|;
name|verifyHeaders
argument_list|(
name|destMessage
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
specifier|private
specifier|static
name|void
name|setupMessageHeader
parameter_list|(
name|Message
name|outMessage
parameter_list|,
name|String
name|correlationId
parameter_list|,
name|String
name|replyTo
parameter_list|)
block|{
name|JMSMessageHeadersType
name|header
init|=
operator|new
name|JMSMessageHeadersType
argument_list|()
decl_stmt|;
name|header
operator|.
name|setJMSCorrelationID
argument_list|(
name|correlationId
argument_list|)
expr_stmt|;
name|header
operator|.
name|setJMSDeliveryMode
argument_list|(
name|DeliveryMode
operator|.
name|PERSISTENT
argument_list|)
expr_stmt|;
name|header
operator|.
name|setJMSPriority
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|header
operator|.
name|setTimeToLive
argument_list|(
literal|1000L
argument_list|)
expr_stmt|;
name|header
operator|.
name|setJMSReplyTo
argument_list|(
name|replyTo
argument_list|)
expr_stmt|;
name|outMessage
operator|.
name|put
argument_list|(
name|JMSConstants
operator|.
name|JMS_CLIENT_REQUEST_HEADERS
argument_list|,
name|header
argument_list|)
expr_stmt|;
name|outMessage
operator|.
name|put
argument_list|(
name|Message
operator|.
name|ENCODING
argument_list|,
literal|"US-ASCII"
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|verifyRequestResponseHeaders
parameter_list|(
name|Message
name|msgIn
parameter_list|,
name|Message
name|msgOut
parameter_list|)
block|{
name|JMSMessageHeadersType
name|outHeader
init|=
operator|(
name|JMSMessageHeadersType
operator|)
name|msgOut
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_CLIENT_REQUEST_HEADERS
argument_list|)
decl_stmt|;
name|String
name|inEncoding
init|=
operator|(
name|String
operator|)
name|msgIn
operator|.
name|get
argument_list|(
name|Message
operator|.
name|ENCODING
argument_list|)
decl_stmt|;
name|String
name|outEncoding
init|=
operator|(
name|String
operator|)
name|msgOut
operator|.
name|get
argument_list|(
name|Message
operator|.
name|ENCODING
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"The message encoding should be equal"
argument_list|,
name|inEncoding
argument_list|,
name|outEncoding
argument_list|)
expr_stmt|;
name|JMSMessageHeadersType
name|inHeader
init|=
operator|(
name|JMSMessageHeadersType
operator|)
name|msgIn
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_CLIENT_RESPONSE_HEADERS
argument_list|)
decl_stmt|;
name|verifyJmsHeaderEquality
argument_list|(
name|outHeader
argument_list|,
name|inHeader
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testRoundTripDestination
parameter_list|()
throws|throws
name|Exception
block|{
name|Message
name|msg
init|=
name|testRoundTripDestination
argument_list|(
literal|true
argument_list|)
decl_stmt|;
name|SecurityContext
name|securityContext
init|=
name|msg
operator|.
name|get
argument_list|(
name|SecurityContext
operator|.
name|class
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"SecurityContext should be set in message received by JMSDestination"
argument_list|,
name|securityContext
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Principal in SecurityContext should be"
argument_list|,
literal|"testUser"
argument_list|,
name|securityContext
operator|.
name|getUserPrincipal
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testRoundTripDestinationDoNotCreateSecurityContext
parameter_list|()
throws|throws
name|Exception
block|{
name|Message
name|msg
init|=
name|testRoundTripDestination
argument_list|(
literal|false
argument_list|)
decl_stmt|;
name|SecurityContext
name|securityContext
init|=
name|msg
operator|.
name|get
argument_list|(
name|SecurityContext
operator|.
name|class
argument_list|)
decl_stmt|;
name|assertNull
argument_list|(
literal|"SecurityContext should not be set in message received by JMSDestination"
argument_list|,
name|securityContext
argument_list|)
expr_stmt|;
block|}
specifier|private
name|Message
name|testRoundTripDestination
parameter_list|(
name|boolean
name|createSecurityContext
parameter_list|)
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldService"
argument_list|,
literal|"HelloWorldPort"
argument_list|)
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|conduit
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|setCreateSecurityContext
argument_list|(
name|createSecurityContext
argument_list|)
expr_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
specifier|final
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
comment|// set up MessageObserver for handling the conduit message
name|MessageObserver
name|observer
init|=
operator|new
name|MessageObserver
argument_list|()
block|{
specifier|public
name|void
name|onMessage
parameter_list|(
name|Message
name|m
parameter_list|)
block|{
name|Exchange
name|exchange
init|=
operator|new
name|ExchangeImpl
argument_list|()
decl_stmt|;
name|exchange
operator|.
name|setInMessage
argument_list|(
name|m
argument_list|)
expr_stmt|;
name|m
operator|.
name|setExchange
argument_list|(
name|exchange
argument_list|)
expr_stmt|;
name|verifyReceivedMessage
argument_list|(
name|m
argument_list|)
expr_stmt|;
name|verifyHeaders
argument_list|(
name|m
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// setup the message for
name|Conduit
name|backConduit
decl_stmt|;
try|try
block|{
name|backConduit
operator|=
name|destination
operator|.
name|getBackChannel
argument_list|(
name|m
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the conduit
name|Message
name|replyMessage
init|=
operator|new
name|MessageImpl
argument_list|()
decl_stmt|;
name|sendOneWayMessage
argument_list|(
name|backConduit
argument_list|,
name|replyMessage
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
block|}
block|}
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|observer
argument_list|)
expr_stmt|;
name|sendMessageSync
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the destination,
comment|// create the thread to handler the Destination incoming message
name|verifyReceivedMessage
argument_list|(
name|waitForReceiveInMessage
argument_list|()
argument_list|)
expr_stmt|;
comment|// wait for a while for the jms session recycling
comment|// Send a second message to check for an issue
comment|// Where the session was closed the second time
name|sendMessageSync
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|Message
name|inMessage
init|=
name|waitForReceiveInMessage
argument_list|()
decl_stmt|;
name|verifyReceivedMessage
argument_list|(
name|inMessage
argument_list|)
expr_stmt|;
comment|// wait for a while for the jms session recycling
comment|//        Thread.sleep(1000L);
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
return|return
name|inMessage
return|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testProperty
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldService"
argument_list|,
literal|"HelloWorldPort"
argument_list|)
decl_stmt|;
specifier|final
name|String
name|customPropertyName
init|=
literal|"THIS_PROPERTY_WILL_NOT_BE_AUTO_COPIED"
decl_stmt|;
comment|// set up the conduit send to be true
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|JMSMessageHeadersType
name|headers
init|=
operator|(
name|JMSMessageHeadersType
operator|)
name|outMessage
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_CLIENT_REQUEST_HEADERS
argument_list|)
decl_stmt|;
name|headers
operator|.
name|putProperty
argument_list|(
name|customPropertyName
argument_list|,
name|customPropertyName
argument_list|)
expr_stmt|;
specifier|final
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
comment|// set up MessageObserver for handling the conduit message
name|MessageObserver
name|observer
init|=
operator|new
name|MessageObserver
argument_list|()
block|{
specifier|public
name|void
name|onMessage
parameter_list|(
name|Message
name|m
parameter_list|)
block|{
name|Exchange
name|exchange
init|=
operator|new
name|ExchangeImpl
argument_list|()
decl_stmt|;
name|exchange
operator|.
name|setInMessage
argument_list|(
name|m
argument_list|)
expr_stmt|;
name|m
operator|.
name|setExchange
argument_list|(
name|exchange
argument_list|)
expr_stmt|;
name|verifyReceivedMessage
argument_list|(
name|m
argument_list|)
expr_stmt|;
name|verifyHeaders
argument_list|(
name|m
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// setup the message for
name|Conduit
name|backConduit
decl_stmt|;
try|try
block|{
name|backConduit
operator|=
name|destination
operator|.
name|getBackChannel
argument_list|(
name|m
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the conduit
name|Message
name|replyMessage
init|=
operator|new
name|MessageImpl
argument_list|()
decl_stmt|;
comment|// copy the message encoding
name|replyMessage
operator|.
name|put
argument_list|(
name|Message
operator|.
name|ENCODING
argument_list|,
name|m
operator|.
name|get
argument_list|(
name|Message
operator|.
name|ENCODING
argument_list|)
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|backConduit
argument_list|,
name|replyMessage
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
block|}
block|}
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|observer
argument_list|)
expr_stmt|;
name|sendMessageSync
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the destination,
comment|// create the thread to handler the Destination incoming message
name|Message
name|inMessage
init|=
name|waitForReceiveInMessage
argument_list|()
decl_stmt|;
name|verifyReceivedMessage
argument_list|(
name|inMessage
argument_list|)
expr_stmt|;
name|verifyRequestResponseHeaders
argument_list|(
name|inMessage
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|JMSMessageHeadersType
name|inHeader
init|=
operator|(
name|JMSMessageHeadersType
operator|)
name|inMessage
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_CLIENT_RESPONSE_HEADERS
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"The inHeader should not be null"
argument_list|,
name|inHeader
argument_list|)
expr_stmt|;
comment|// TODO we need to check the SOAP JMS transport properties here
comment|// wait for a while for the jms session recycling
comment|//        Thread.sleep(1000L);
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testIsMultiplexCapable
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldService"
argument_list|,
literal|"HelloWorldPort"
argument_list|)
decl_stmt|;
specifier|final
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"is multiplex"
argument_list|,
name|destination
operator|instanceof
name|MultiplexDestination
argument_list|)
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testSecurityContext
parameter_list|()
throws|throws
name|Exception
block|{
name|SecurityContext
name|ctx
init|=
name|testSecurityContext
argument_list|(
literal|true
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"SecurityContext should be set in message received by JMSDestination"
argument_list|,
name|ctx
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"Principal in SecurityContext should be"
argument_list|,
literal|"testUser"
argument_list|,
name|ctx
operator|.
name|getUserPrincipal
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testDoNotCreateSecurityContext
parameter_list|()
throws|throws
name|Exception
block|{
name|SecurityContext
name|ctx
init|=
name|testSecurityContext
argument_list|(
literal|false
argument_list|)
decl_stmt|;
name|assertNull
argument_list|(
literal|"SecurityContext should not be set in message received by JMSDestination"
argument_list|,
name|ctx
argument_list|)
expr_stmt|;
block|}
specifier|private
name|SecurityContext
name|testSecurityContext
parameter_list|(
name|boolean
name|createSecurityContext
parameter_list|)
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldService"
argument_list|,
literal|"HelloWorldPort"
argument_list|)
decl_stmt|;
specifier|final
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|setCreateSecurityContext
argument_list|(
name|createSecurityContext
argument_list|)
expr_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
comment|// set up the conduit send to be true
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|Message
name|destMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
name|SecurityContext
name|securityContext
init|=
name|destMessage
operator|.
name|get
argument_list|(
name|SecurityContext
operator|.
name|class
argument_list|)
decl_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
return|return
name|securityContext
return|;
block|}
annotation|@
name|Test
annotation|@
name|Ignore
specifier|public
name|void
name|testOneWayReplyToSetUnset
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* 1. Test that replyTo destination set in WSDL is NOT used          * in spec compliant mode */
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HWStaticReplyQBinMsgService"
argument_list|,
literal|"HWStaticReplyQBinMsgPort"
argument_list|)
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|Message
name|destMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
comment|// just verify the Destination inMessage
name|assertNotNull
argument_list|(
literal|"The destination should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|verifyReplyToNotSet
argument_list|(
name|destMessage
argument_list|)
expr_stmt|;
comment|/* 2. Test that replyTo destination set in WSDL IS used          * in spec non-compliant mode */
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|destMessage
operator|=
name|waitForReceiveDestMessage
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
literal|"The destination should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|String
name|exName
init|=
name|getQueueName
argument_list|(
name|conduit
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|getReplyDestination
argument_list|()
argument_list|)
decl_stmt|;
name|verifyReplyToSet
argument_list|(
name|destMessage
argument_list|,
name|Queue
operator|.
name|class
argument_list|,
name|exName
argument_list|)
expr_stmt|;
comment|/* 3. Test that replyTo destination provided via invocation context          * overrides the value set in WSDL and IS used in spec non-compliant mode */
name|String
name|contextReplyTo
init|=
name|conduit
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|getReplyDestination
argument_list|()
operator|+
literal|".context"
decl_stmt|;
name|exName
operator|+=
literal|".context"
expr_stmt|;
name|setupMessageHeader
argument_list|(
name|outMessage
argument_list|,
literal|"cidValue"
argument_list|,
name|contextReplyTo
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|destMessage
operator|=
name|waitForReceiveDestMessage
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
literal|"The destiantion should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|verifyReplyToSet
argument_list|(
name|destMessage
argument_list|,
name|Queue
operator|.
name|class
argument_list|,
name|exName
argument_list|)
expr_stmt|;
comment|/* 4. Test that replyTo destination provided via invocation context          * and the value set in WSDL are NOT used in spec non-compliant mode          * when JMSConstants.JMS_SET_REPLY_TO == false */
name|setupMessageHeader
argument_list|(
name|outMessage
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|outMessage
operator|.
name|put
argument_list|(
name|JMSConstants
operator|.
name|JMS_SET_REPLY_TO
argument_list|,
name|Boolean
operator|.
name|FALSE
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|destMessage
operator|=
name|waitForReceiveDestMessage
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
literal|"The destiantion should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|verifyReplyToNotSet
argument_list|(
name|destMessage
argument_list|)
expr_stmt|;
comment|/* 5. Test that replyTo destination set in WSDL IS used in spec non-compliant          * mode when JMSConstants.JMS_SET_REPLY_TO == true */
name|setupMessageHeader
argument_list|(
name|outMessage
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|outMessage
operator|.
name|put
argument_list|(
name|JMSConstants
operator|.
name|JMS_SET_REPLY_TO
argument_list|,
name|Boolean
operator|.
name|TRUE
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|destMessage
operator|=
name|waitForReceiveDestMessage
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
literal|"The destiantion should have got the message "
argument_list|,
name|destMessage
argument_list|)
expr_stmt|;
name|exName
operator|=
name|getQueueName
argument_list|(
name|conduit
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|getReplyDestination
argument_list|()
argument_list|)
expr_stmt|;
name|verifyReplyToSet
argument_list|(
name|destMessage
argument_list|,
name|Queue
operator|.
name|class
argument_list|,
name|exName
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testMessageObserverExceptionHandling
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|CountDownLatch
name|latch
init|=
operator|new
name|CountDownLatch
argument_list|(
literal|1
argument_list|)
decl_stmt|;
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
operator|new
name|MessageObserver
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|onMessage
parameter_list|(
name|Message
name|message
parameter_list|)
block|{
try|try
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Error!"
argument_list|)
throw|;
block|}
finally|finally
block|{
name|latch
operator|.
name|countDown
argument_list|()
expr_stmt|;
block|}
block|}
block|}
argument_list|)
expr_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|Thread
operator|.
name|sleep
argument_list|(
literal|500L
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
name|latch
operator|.
name|await
argument_list|(
literal|5
argument_list|,
name|TimeUnit
operator|.
name|SECONDS
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testConnectionFactoryExceptionHandling
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
specifier|final
name|Function
argument_list|<
name|ConnectionFactory
argument_list|,
name|ConnectionFactory
argument_list|>
name|wrapper
init|=
operator|new
name|Function
argument_list|<
name|ConnectionFactory
argument_list|,
name|ConnectionFactory
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|ConnectionFactory
name|apply
parameter_list|(
name|ConnectionFactory
name|cf
parameter_list|)
block|{
return|return
operator|new
name|FaultyConnectionFactory
argument_list|(
name|cf
argument_list|,
literal|3
argument_list|)
return|;
block|}
block|}
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|,
name|wrapper
argument_list|)
decl_stmt|;
name|destination
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|setRetryInterval
argument_list|(
literal|1000
argument_list|)
expr_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|Thread
operator|.
name|sleep
argument_list|(
literal|4000L
argument_list|)
expr_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the destination,
comment|// create the thread to handler the Destination incoming message
name|Message
name|inMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
name|verifyReceivedMessage
argument_list|(
name|inMessage
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBrokerExceptionHandling
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|)
decl_stmt|;
name|destination
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|setRetryInterval
argument_list|(
literal|1000
argument_list|)
expr_stmt|;
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
name|Thread
operator|.
name|sleep
argument_list|(
literal|500L
argument_list|)
expr_stmt|;
name|broker
operator|.
name|stopAllConnectors
argument_list|(
operator|new
name|ServiceStopper
argument_list|()
argument_list|)
expr_stmt|;
name|broker
operator|.
name|startAllConnectors
argument_list|()
expr_stmt|;
name|Thread
operator|.
name|sleep
argument_list|(
literal|2000L
argument_list|)
expr_stmt|;
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
comment|// wait for the message to be got from the destination,
comment|// create the thread to handler the Destination incoming message
name|Message
name|inMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
name|verifyReceivedMessage
argument_list|(
name|inMessage
argument_list|)
expr_stmt|;
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testSessionsExceptionHandling
parameter_list|()
throws|throws
name|Exception
block|{
name|EndpointInfo
name|ei
init|=
name|setupServiceInfo
argument_list|(
literal|"HelloWorldPubSubService"
argument_list|,
literal|"HelloWorldPubSubPort"
argument_list|)
decl_stmt|;
specifier|final
name|AtomicInteger
name|latch
init|=
operator|new
name|AtomicInteger
argument_list|(
literal|1
argument_list|)
decl_stmt|;
specifier|final
name|Function
argument_list|<
name|Connection
argument_list|,
name|Connection
argument_list|>
name|connection
init|=
name|c
lambda|->
operator|new
name|FaultyConnection
argument_list|(
name|c
argument_list|)
block|{
block|@Override                 public Session createSession(boolean transacted
decl_stmt|,
name|int
name|acknowledgeMode
decl_stmt|)
throws|throws
name|JMSException
block|{
comment|// Fail only once
decl_stmt|if (latch.getAndDecrement(
block|)
function|== 0
block|)
block|{
throw|throw
operator|new
name|JMSException
argument_list|(
literal|"createSession() failed (simulated)"
argument_list|)
throw|;
block|}
end_class

begin_else
else|else
block|{
return|return
name|super
operator|.
name|createSession
argument_list|(
name|transacted
argument_list|,
name|acknowledgeMode
argument_list|)
return|;
block|}
end_else

begin_empty_stmt
unit|}             }
empty_stmt|;
end_empty_stmt

begin_decl_stmt
specifier|final
name|Function
argument_list|<
name|ConnectionFactory
argument_list|,
name|ConnectionFactory
argument_list|>
name|wrapper
init|=
operator|new
name|Function
argument_list|<
name|ConnectionFactory
argument_list|,
name|ConnectionFactory
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|ConnectionFactory
name|apply
parameter_list|(
name|ConnectionFactory
name|cf
parameter_list|)
block|{
return|return
operator|new
name|FaultyConnectionFactory
argument_list|(
name|cf
argument_list|,
name|connection
argument_list|,
literal|0
argument_list|)
return|;
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|JMSConduit
name|conduit
init|=
name|setupJMSConduitWithObserver
argument_list|(
name|ei
argument_list|)
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|JMSDestination
name|destination
init|=
name|setupJMSDestination
argument_list|(
name|ei
argument_list|,
name|wrapper
argument_list|)
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|destination
operator|.
name|getJmsConfig
argument_list|()
operator|.
name|setRetryInterval
argument_list|(
literal|1000
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|destination
operator|.
name|setMessageObserver
argument_list|(
name|createMessageObserver
argument_list|()
argument_list|)
expr_stmt|;
end_expr_stmt

begin_decl_stmt
specifier|final
name|Message
name|outMessage
init|=
name|createMessage
argument_list|()
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|Thread
operator|.
name|sleep
argument_list|(
literal|4000L
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|sendOneWayMessage
argument_list|(
name|conduit
argument_list|,
name|outMessage
argument_list|)
expr_stmt|;
end_expr_stmt

begin_comment
comment|// wait for the message to be got from the destination,
end_comment

begin_comment
comment|// create the thread to handler the Destination incoming message
end_comment

begin_decl_stmt
name|Message
name|inMessage
init|=
name|waitForReceiveDestMessage
argument_list|()
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|verifyReceivedMessage
argument_list|(
name|inMessage
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|conduit
operator|.
name|close
argument_list|()
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|destination
operator|.
name|shutdown
argument_list|()
expr_stmt|;
end_expr_stmt

begin_function
unit|}       private
name|String
name|getQueueName
parameter_list|(
name|String
name|exName
parameter_list|)
block|{
if|if
condition|(
name|exName
operator|==
literal|null
condition|)
block|{
return|return
literal|null
return|;
block|}
return|return
operator|(
name|exName
operator|.
name|indexOf
argument_list|(
literal|'/'
argument_list|)
operator|!=
operator|-
literal|1
operator|&&
name|exName
operator|.
name|indexOf
argument_list|(
literal|'/'
argument_list|)
operator|<
name|exName
operator|.
name|length
argument_list|()
operator|)
condition|?
name|exName
operator|.
name|substring
argument_list|(
name|exName
operator|.
name|indexOf
argument_list|(
literal|'/'
argument_list|)
operator|+
literal|1
argument_list|)
else|:
name|exName
return|;
block|}
end_function

begin_function
specifier|protected
name|void
name|verifyReplyToNotSet
parameter_list|(
name|Message
name|cxfMsg
parameter_list|)
block|{
name|javax
operator|.
name|jms
operator|.
name|Message
name|jmsMsg
init|=
name|javax
operator|.
name|jms
operator|.
name|Message
operator|.
name|class
operator|.
name|cast
argument_list|(
name|cxfMsg
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_REQUEST_MESSAGE
argument_list|)
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"JMS Messsage must be null"
argument_list|,
name|jmsMsg
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|private
name|String
name|getDestinationName
parameter_list|(
name|Destination
name|dest
parameter_list|)
throws|throws
name|JMSException
block|{
if|if
condition|(
name|dest
operator|instanceof
name|Queue
condition|)
block|{
return|return
operator|(
operator|(
name|Queue
operator|)
name|dest
operator|)
operator|.
name|getQueueName
argument_list|()
return|;
block|}
return|return
operator|(
operator|(
name|Topic
operator|)
name|dest
operator|)
operator|.
name|getTopicName
argument_list|()
return|;
block|}
end_function

begin_function
specifier|protected
name|void
name|verifyReplyToSet
parameter_list|(
name|Message
name|cxfMsg
parameter_list|,
name|Class
argument_list|<
name|?
extends|extends
name|Destination
argument_list|>
name|type
parameter_list|,
name|String
name|expectedName
parameter_list|)
throws|throws
name|Exception
block|{
name|javax
operator|.
name|jms
operator|.
name|Message
name|jmsMsg
init|=
name|javax
operator|.
name|jms
operator|.
name|Message
operator|.
name|class
operator|.
name|cast
argument_list|(
name|cxfMsg
operator|.
name|get
argument_list|(
name|JMSConstants
operator|.
name|JMS_REQUEST_MESSAGE
argument_list|)
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"JMS Messsage must not be null"
argument_list|,
name|jmsMsg
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
literal|"JMS Messsage's replyTo must not be null"
argument_list|,
name|jmsMsg
operator|.
name|getJMSReplyTo
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"JMS Messsage's replyTo type must be of type "
operator|+
name|type
operator|.
name|getName
argument_list|()
argument_list|,
name|type
operator|.
name|isAssignableFrom
argument_list|(
name|jmsMsg
operator|.
name|getJMSReplyTo
argument_list|()
operator|.
name|getClass
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|String
name|receivedName
init|=
name|getDestinationName
argument_list|(
name|jmsMsg
operator|.
name|getJMSReplyTo
argument_list|()
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"JMS Messsage's replyTo must be named "
operator|+
name|expectedName
operator|+
literal|" but was "
operator|+
name|receivedName
argument_list|,
name|expectedName
operator|==
name|receivedName
operator|||
name|receivedName
operator|.
name|equals
argument_list|(
name|expectedName
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

unit|}
end_unit

