begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
package|;
end_package

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|SimpleDateFormat
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
operator|.
name|sql
operator|.
name|SQLPrinterVisitor
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|SearchUtils
block|{
specifier|public
specifier|static
specifier|final
name|String
name|DATE_FORMAT_PROPERTY
init|=
literal|"search.date-format"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|TIMEZONE_SUPPORT_PROPERTY
init|=
literal|"search.timezone.support"
decl_stmt|;
specifier|private
name|SearchUtils
parameter_list|()
block|{              }
specifier|public
specifier|static
name|SimpleDateFormat
name|getDateFormat
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|String
name|defaultFormat
parameter_list|)
block|{
name|String
name|dfProperty
init|=
name|properties
operator|.
name|get
argument_list|(
name|DATE_FORMAT_PROPERTY
argument_list|)
decl_stmt|;
return|return
operator|new
name|SimpleDateFormat
argument_list|(
name|dfProperty
operator|==
literal|null
condition|?
name|defaultFormat
else|:
name|dfProperty
argument_list|)
return|;
block|}
specifier|public
specifier|static
name|boolean
name|isTimeZoneSupported
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|Boolean
name|defaultValue
parameter_list|)
block|{
name|String
name|tzProperty
init|=
name|properties
operator|.
name|get
argument_list|(
name|SearchUtils
operator|.
name|TIMEZONE_SUPPORT_PROPERTY
argument_list|)
decl_stmt|;
return|return
name|tzProperty
operator|==
literal|null
condition|?
name|defaultValue
else|:
name|Boolean
operator|.
name|valueOf
argument_list|(
name|tzProperty
argument_list|)
return|;
block|}
specifier|public
specifier|static
parameter_list|<
name|T
parameter_list|>
name|String
name|toSQL
parameter_list|(
name|SearchCondition
argument_list|<
name|T
argument_list|>
name|sc
parameter_list|,
name|String
name|table
parameter_list|,
name|String
modifier|...
name|columns
parameter_list|)
block|{
name|SearchConditionVisitor
argument_list|<
name|T
argument_list|>
name|visitor
init|=
operator|new
name|SQLPrinterVisitor
argument_list|<
name|T
argument_list|>
argument_list|(
name|table
argument_list|,
name|columns
argument_list|)
decl_stmt|;
name|sc
operator|.
name|accept
argument_list|(
name|visitor
argument_list|)
expr_stmt|;
return|return
name|visitor
operator|.
name|getResult
argument_list|()
return|;
block|}
specifier|public
specifier|static
name|void
name|startSqlQuery
parameter_list|(
name|StringBuilder
name|sb
parameter_list|,
name|String
name|table
parameter_list|,
name|String
modifier|...
name|columns
parameter_list|)
block|{
name|sb
operator|.
name|append
argument_list|(
literal|"SELECT "
argument_list|)
expr_stmt|;
if|if
condition|(
name|columns
operator|.
name|length
operator|>
literal|0
condition|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|columns
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|sb
operator|.
name|append
argument_list|(
name|columns
index|[
name|i
index|]
argument_list|)
expr_stmt|;
if|if
condition|(
name|i
operator|+
literal|1
operator|<
name|columns
operator|.
name|length
condition|)
block|{
name|sb
operator|.
name|append
argument_list|(
literal|","
argument_list|)
expr_stmt|;
block|}
block|}
block|}
else|else
block|{
name|sb
operator|.
name|append
argument_list|(
literal|"*"
argument_list|)
expr_stmt|;
block|}
name|sb
operator|.
name|append
argument_list|(
literal|" FROM "
argument_list|)
operator|.
name|append
argument_list|(
name|table
argument_list|)
operator|.
name|append
argument_list|(
literal|" WHERE "
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
name|String
name|conditionTypeToSqlOperator
parameter_list|(
name|ConditionType
name|ct
parameter_list|,
name|String
name|value
parameter_list|)
block|{
comment|// TODO : if we have the same column involved, ex a>= 123 and a<=244 then
comment|// we may try to use IN or BETWEEN, depending on the values
name|String
name|op
decl_stmt|;
switch|switch
condition|(
name|ct
condition|)
block|{
case|case
name|EQUALS
case|:
name|op
operator|=
name|value
operator|.
name|contains
argument_list|(
literal|"%"
argument_list|)
condition|?
literal|"LIKE"
else|:
literal|"="
expr_stmt|;
break|break;
case|case
name|NOT_EQUALS
case|:
name|op
operator|=
name|value
operator|.
name|contains
argument_list|(
literal|"%"
argument_list|)
condition|?
literal|"NOT LIKE"
else|:
literal|"<>"
expr_stmt|;
break|break;
case|case
name|GREATER_THAN
case|:
name|op
operator|=
literal|">"
expr_stmt|;
break|break;
case|case
name|GREATER_OR_EQUALS
case|:
name|op
operator|=
literal|">="
expr_stmt|;
break|break;
case|case
name|LESS_THAN
case|:
name|op
operator|=
literal|"<"
expr_stmt|;
break|break;
case|case
name|LESS_OR_EQUALS
case|:
name|op
operator|=
literal|"<="
expr_stmt|;
break|break;
default|default:
name|String
name|msg
init|=
name|String
operator|.
name|format
argument_list|(
literal|"Condition type %s is not supported"
argument_list|,
name|ct
operator|.
name|name
argument_list|()
argument_list|)
decl_stmt|;
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|msg
argument_list|)
throw|;
block|}
return|return
name|op
return|;
block|}
block|}
end_class

end_unit

