begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|transfer
operator|.
name|validationtransformation
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|logging
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|annotation
operator|.
name|Resource
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|transform
operator|.
name|Source
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|transform
operator|.
name|Templates
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|transform
operator|.
name|TransformerConfigurationException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|transform
operator|.
name|TransformerFactory
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|WebServiceContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|binding
operator|.
name|soap
operator|.
name|SoapFault
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|binding
operator|.
name|soap
operator|.
name|SoapMessage
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|binding
operator|.
name|soap
operator|.
name|SoapVersion
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|logging
operator|.
name|LogUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|feature
operator|.
name|transform
operator|.
name|XSLTUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|helpers
operator|.
name|DOMUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxws
operator|.
name|context
operator|.
name|WrappedMessageContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|transfer
operator|.
name|Representation
import|;
end_import

begin_comment
comment|/**  * Implementation of the ResourceTransformer for the XSL transformation.  */
end_comment

begin_class
specifier|public
class|class
name|XSLTResourceTransformer
implements|implements
name|ResourceTransformer
block|{
specifier|private
specifier|static
specifier|final
name|Logger
name|LOG
init|=
name|LogUtils
operator|.
name|getL7dLogger
argument_list|(
name|XSLTResourceTransformer
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|protected
name|Templates
name|templates
decl_stmt|;
specifier|protected
name|ResourceValidator
name|validator
decl_stmt|;
annotation|@
name|Resource
specifier|private
name|WebServiceContext
name|context
decl_stmt|;
specifier|public
name|XSLTResourceTransformer
parameter_list|(
name|Source
name|xsl
parameter_list|)
block|{
name|this
argument_list|(
name|xsl
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
specifier|public
name|XSLTResourceTransformer
parameter_list|(
name|Source
name|xsl
parameter_list|,
name|ResourceValidator
name|validator
parameter_list|)
block|{
name|this
operator|.
name|validator
operator|=
name|validator
expr_stmt|;
try|try
block|{
name|templates
operator|=
name|TransformerFactory
operator|.
name|newInstance
argument_list|()
operator|.
name|newTemplates
argument_list|(
name|xsl
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|TransformerConfigurationException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|severe
argument_list|(
name|e
operator|.
name|getLocalizedMessage
argument_list|()
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|SoapFault
argument_list|(
literal|"Internal error"
argument_list|,
name|getSoapVersion
argument_list|()
operator|.
name|getReceiver
argument_list|()
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|ResourceValidator
name|transform
parameter_list|(
name|Representation
name|newRepresentation
parameter_list|,
name|Representation
name|oldRepresentation
parameter_list|)
block|{
name|Document
name|doc
init|=
name|DOMUtils
operator|.
name|createDocument
argument_list|()
decl_stmt|;
name|Node
name|representation
init|=
operator|(
name|Node
operator|)
name|newRepresentation
operator|.
name|getAny
argument_list|()
decl_stmt|;
name|Node
name|importedNode
init|=
name|doc
operator|.
name|importNode
argument_list|(
name|representation
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|doc
operator|.
name|appendChild
argument_list|(
name|importedNode
argument_list|)
expr_stmt|;
name|Document
name|result
init|=
name|XSLTUtils
operator|.
name|transform
argument_list|(
name|templates
argument_list|,
name|doc
argument_list|)
decl_stmt|;
name|newRepresentation
operator|.
name|setAny
argument_list|(
name|result
operator|.
name|getDocumentElement
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|validator
return|;
block|}
specifier|private
name|SoapVersion
name|getSoapVersion
parameter_list|()
block|{
name|WrappedMessageContext
name|wmc
init|=
operator|(
name|WrappedMessageContext
operator|)
name|context
operator|.
name|getMessageContext
argument_list|()
decl_stmt|;
name|SoapMessage
name|message
init|=
operator|(
name|SoapMessage
operator|)
name|wmc
operator|.
name|getWrappedMessage
argument_list|()
decl_stmt|;
return|return
name|message
operator|.
name|getVersion
argument_list|()
return|;
block|}
block|}
end_class

end_unit

