begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rs
operator|.
name|security
operator|.
name|oauth2
operator|.
name|tokens
operator|.
name|hawk
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rs
operator|.
name|security
operator|.
name|oauth2
operator|.
name|utils
operator|.
name|OAuthConstants
import|;
end_import

begin_enum
specifier|public
enum|enum
name|HmacAlgorithm
block|{
name|HmacSHA1
parameter_list|(
name|OAuthConstants
operator|.
name|HMAC_ALGO_SHA_1
parameter_list|)
operator|,
constructor|HmacSHA256(OAuthConstants.HMAC_ALGO_SHA_256
block|)
enum|;
end_enum

begin_decl_stmt
specifier|private
specifier|final
name|String
name|oauthName
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|HmacAlgorithm
argument_list|(
name|String
name|oauthName
argument_list|)
block|{
name|this
operator|.
name|oauthName
operator|=
name|oauthName
block|;     }
specifier|public
name|String
name|getOAuthName
argument_list|()
block|{
return|return
name|oauthName
return|;
block|}
end_expr_stmt

begin_function
specifier|public
name|String
name|getJavaName
parameter_list|()
block|{
return|return
name|name
argument_list|()
return|;
block|}
end_function

begin_function
specifier|public
specifier|static
name|HmacAlgorithm
name|toHmacAlgorithm
parameter_list|(
name|String
name|value
parameter_list|)
block|{
if|if
condition|(
name|OAuthConstants
operator|.
name|HMAC_ALGO_SHA_1
operator|.
name|equals
argument_list|(
name|value
argument_list|)
condition|)
block|{
return|return
name|HmacSHA1
return|;
block|}
if|if
condition|(
name|OAuthConstants
operator|.
name|HMAC_ALGO_SHA_256
operator|.
name|equals
argument_list|(
name|value
argument_list|)
condition|)
block|{
return|return
name|HmacSHA256
return|;
block|}
return|return
literal|null
return|;
block|}
end_function

unit|}
end_unit

