begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|resources
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|GET
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|Path
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|Produces
import|;
end_import

begin_class
annotation|@
name|Path
argument_list|(
literal|"/{a}/{b}/{c}/d"
argument_list|)
specifier|public
class|class
name|TestResource
block|{
specifier|public
name|TestResource
parameter_list|()
block|{     }
annotation|@
name|Path
argument_list|(
literal|"/resource"
argument_list|)
specifier|public
name|TestResource
name|subresource
parameter_list|()
block|{
return|return
name|this
return|;
block|}
annotation|@
name|Path
argument_list|(
literal|"/resource"
argument_list|)
annotation|@
name|GET
annotation|@
name|Produces
argument_list|(
literal|"application/json"
argument_list|)
specifier|public
name|String
name|resourceMethod
parameter_list|()
block|{
return|return
literal|""
return|;
block|}
annotation|@
name|Path
argument_list|(
literal|"/resource2/1/{b}"
argument_list|)
specifier|public
name|TestResource
name|subresource2
parameter_list|()
block|{
return|return
name|this
return|;
block|}
annotation|@
name|Path
argument_list|(
literal|"/resource2/{a}/{b}"
argument_list|)
annotation|@
name|GET
annotation|@
name|Produces
argument_list|(
literal|"application/json"
argument_list|)
specifier|public
name|String
name|resourceMethod2
parameter_list|()
block|{
return|return
literal|""
return|;
block|}
annotation|@
name|GET
annotation|@
name|Produces
argument_list|(
literal|"application/xml"
argument_list|)
annotation|@
name|Path
argument_list|(
literal|"/resource1"
argument_list|)
specifier|public
name|TestResource
name|xmlResource
parameter_list|()
block|{
return|return
name|this
return|;
block|}
annotation|@
name|Path
argument_list|(
literal|"/resource1"
argument_list|)
annotation|@
name|GET
annotation|@
name|Produces
argument_list|(
literal|"application/json"
argument_list|)
specifier|public
name|String
name|jsonResource
parameter_list|()
block|{
return|return
literal|""
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"/"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/xml"
argument_list|)
specifier|public
name|String
name|listMethod
parameter_list|()
block|{
return|return
literal|"This is a list method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"/{e}"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/xml"
argument_list|)
specifier|public
name|String
name|readMethod
parameter_list|()
block|{
return|return
literal|"This is a list method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"/{a}/{b}"
argument_list|)
specifier|public
name|String
name|limitedPath
parameter_list|()
block|{
return|return
literal|"This is a list method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
name|value
operator|=
literal|"/{e}"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/json"
argument_list|)
specifier|public
name|String
name|unlimitedPath
parameter_list|()
block|{
return|return
literal|"This is a list method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"/{e}/bar/baz/baz"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/json"
argument_list|)
specifier|public
name|String
name|readMethod2
parameter_list|()
block|{
return|return
literal|"This is a list method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"{id:custom}"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/bar"
argument_list|)
specifier|public
name|String
name|readBar
parameter_list|()
block|{
return|return
literal|"This is a bar method"
return|;
block|}
annotation|@
name|GET
annotation|@
name|Path
argument_list|(
literal|"{id:custom}"
argument_list|)
annotation|@
name|Produces
argument_list|(
literal|"application/foo"
argument_list|)
specifier|public
name|String
name|readFoo
parameter_list|()
block|{
return|return
literal|"This is a foo method"
return|;
block|}
block|}
end_class

end_unit

