begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|wsdlto
operator|.
name|frontend
operator|.
name|jaxws
operator|.
name|processor
operator|.
name|internal
operator|.
name|mapper
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|service
operator|.
name|model
operator|.
name|InterfaceInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|common
operator|.
name|ToolConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|common
operator|.
name|ToolContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|common
operator|.
name|model
operator|.
name|JavaInterface
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|util
operator|.
name|NameUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|wsdlto
operator|.
name|frontend
operator|.
name|jaxws
operator|.
name|processor
operator|.
name|internal
operator|.
name|ProcessorUtil
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|InterfaceMapper
block|{
specifier|private
name|ToolContext
name|context
decl_stmt|;
specifier|public
name|InterfaceMapper
parameter_list|(
name|ToolContext
name|c
parameter_list|)
block|{
name|this
operator|.
name|context
operator|=
name|c
expr_stmt|;
block|}
specifier|public
name|JavaInterface
name|map
parameter_list|(
name|InterfaceInfo
name|interfaceInfo
parameter_list|)
block|{
name|JavaInterface
name|intf
init|=
operator|new
name|JavaInterface
argument_list|()
decl_stmt|;
name|String
name|namespace
init|=
name|interfaceInfo
operator|.
name|getName
argument_list|()
operator|.
name|getNamespaceURI
argument_list|()
decl_stmt|;
name|String
name|packageName
init|=
name|ProcessorUtil
operator|.
name|parsePackageName
argument_list|(
name|namespace
argument_list|,
name|context
operator|.
name|mapPackageName
argument_list|(
name|namespace
argument_list|)
argument_list|)
decl_stmt|;
name|String
name|loc
init|=
operator|(
name|String
operator|)
name|context
operator|.
name|get
argument_list|(
name|ToolConstants
operator|.
name|CFG_WSDLLOCATION
argument_list|)
decl_stmt|;
if|if
condition|(
name|loc
operator|==
literal|null
condition|)
block|{
name|loc
operator|=
operator|(
name|String
operator|)
name|context
operator|.
name|get
argument_list|(
name|ToolConstants
operator|.
name|CFG_WSDLURL
argument_list|)
expr_stmt|;
block|}
name|String
name|webServiceName
init|=
name|interfaceInfo
operator|.
name|getName
argument_list|()
operator|.
name|getLocalPart
argument_list|()
decl_stmt|;
name|intf
operator|.
name|setWebServiceName
argument_list|(
name|webServiceName
argument_list|)
expr_stmt|;
name|intf
operator|.
name|setName
argument_list|(
name|NameUtil
operator|.
name|mangleNameToClassName
argument_list|(
name|webServiceName
argument_list|)
argument_list|)
expr_stmt|;
name|intf
operator|.
name|setNamespace
argument_list|(
name|namespace
argument_list|)
expr_stmt|;
name|intf
operator|.
name|setPackageName
argument_list|(
name|packageName
argument_list|)
expr_stmt|;
name|intf
operator|.
name|setLocation
argument_list|(
name|loc
argument_list|)
expr_stmt|;
return|return
name|intf
return|;
block|}
block|}
end_class

end_unit

