begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxws
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URL
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|BindingProvider
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|WebServiceException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|soap
operator|.
name|SOAPBinding
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|binding
operator|.
name|soap
operator|.
name|Soap12
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|calculator
operator|.
name|CalculatorPortType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|SOAPBindingTest
extends|extends
name|AbstractJaxWsTest
block|{
specifier|private
specifier|static
specifier|final
name|QName
name|SERVICE_1
init|=
operator|new
name|QName
argument_list|(
literal|"http://apache.org/cxf/calculator"
argument_list|,
literal|"CalculatorService"
argument_list|)
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|QName
name|PORT_1
init|=
operator|new
name|QName
argument_list|(
literal|"http://apache.org/cxf/calculator"
argument_list|,
literal|"CalculatorPort"
argument_list|)
decl_stmt|;
annotation|@
name|Test
specifier|public
name|void
name|testRoles
parameter_list|()
throws|throws
name|Exception
block|{
name|URL
name|wsdl1
init|=
name|getClass
argument_list|()
operator|.
name|getResource
argument_list|(
literal|"/wsdl/calculator.wsdl"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|wsdl1
argument_list|)
expr_stmt|;
name|ServiceImpl
name|service
init|=
operator|new
name|ServiceImpl
argument_list|(
name|getBus
argument_list|()
argument_list|,
name|wsdl1
argument_list|,
name|SERVICE_1
argument_list|,
name|ServiceImpl
operator|.
name|class
argument_list|)
decl_stmt|;
name|CalculatorPortType
name|cal
init|=
operator|(
name|CalculatorPortType
operator|)
name|service
operator|.
name|getPort
argument_list|(
name|PORT_1
argument_list|,
name|CalculatorPortType
operator|.
name|class
argument_list|)
decl_stmt|;
name|BindingProvider
name|bindingProvider
init|=
operator|(
name|BindingProvider
operator|)
name|cal
decl_stmt|;
name|assertTrue
argument_list|(
name|bindingProvider
operator|.
name|getBinding
argument_list|()
operator|instanceof
name|SOAPBinding
argument_list|)
expr_stmt|;
name|SOAPBinding
name|binding
init|=
operator|(
name|SOAPBinding
operator|)
name|bindingProvider
operator|.
name|getBinding
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|contains
argument_list|(
name|Soap12
operator|.
name|getInstance
argument_list|()
operator|.
name|getNextRole
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|contains
argument_list|(
name|Soap12
operator|.
name|getInstance
argument_list|()
operator|.
name|getUltimateReceiverRole
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|String
name|myrole
init|=
literal|"http://myrole"
decl_stmt|;
name|Set
argument_list|<
name|String
argument_list|>
name|roles
init|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
name|roles
operator|.
name|add
argument_list|(
name|myrole
argument_list|)
expr_stmt|;
name|binding
operator|.
name|setRoles
argument_list|(
name|roles
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|3
argument_list|,
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|contains
argument_list|(
name|myrole
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|contains
argument_list|(
name|Soap12
operator|.
name|getInstance
argument_list|()
operator|.
name|getNextRole
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|binding
operator|.
name|getRoles
argument_list|()
operator|.
name|contains
argument_list|(
name|Soap12
operator|.
name|getInstance
argument_list|()
operator|.
name|getUltimateReceiverRole
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|roles
operator|.
name|add
argument_list|(
name|Soap12
operator|.
name|getInstance
argument_list|()
operator|.
name|getNoneRole
argument_list|()
argument_list|)
expr_stmt|;
try|try
block|{
name|binding
operator|.
name|setRoles
argument_list|(
name|roles
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"did not throw exception"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|WebServiceException
name|e
parameter_list|)
block|{
comment|// that's expected with none role
block|}
block|}
annotation|@
name|Test
specifier|public
name|void
name|testSAAJ
parameter_list|()
throws|throws
name|Exception
block|{
name|URL
name|wsdl1
init|=
name|getClass
argument_list|()
operator|.
name|getResource
argument_list|(
literal|"/wsdl/calculator.wsdl"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|wsdl1
argument_list|)
expr_stmt|;
name|ServiceImpl
name|service
init|=
operator|new
name|ServiceImpl
argument_list|(
name|getBus
argument_list|()
argument_list|,
name|wsdl1
argument_list|,
name|SERVICE_1
argument_list|,
name|ServiceImpl
operator|.
name|class
argument_list|)
decl_stmt|;
name|CalculatorPortType
name|cal
init|=
operator|(
name|CalculatorPortType
operator|)
name|service
operator|.
name|getPort
argument_list|(
name|PORT_1
argument_list|,
name|CalculatorPortType
operator|.
name|class
argument_list|)
decl_stmt|;
name|BindingProvider
name|bindingProvider
init|=
operator|(
name|BindingProvider
operator|)
name|cal
decl_stmt|;
name|assertTrue
argument_list|(
name|bindingProvider
operator|.
name|getBinding
argument_list|()
operator|instanceof
name|SOAPBinding
argument_list|)
expr_stmt|;
name|SOAPBinding
name|binding
init|=
operator|(
name|SOAPBinding
operator|)
name|bindingProvider
operator|.
name|getBinding
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|binding
operator|.
name|getMessageFactory
argument_list|()
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|binding
operator|.
name|getSOAPFactory
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

