begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|security
operator|.
name|policy
operator|.
name|builders
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Element
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|helpers
operator|.
name|DOMUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|security
operator|.
name|policy
operator|.
name|SP11Constants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|security
operator|.
name|policy
operator|.
name|SP12Constants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|security
operator|.
name|policy
operator|.
name|SPConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|security
operator|.
name|policy
operator|.
name|model
operator|.
name|X509Token
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|neethi
operator|.
name|Assertion
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|neethi
operator|.
name|AssertionBuilderFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|neethi
operator|.
name|Policy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|neethi
operator|.
name|builders
operator|.
name|AssertionBuilder
import|;
end_import

begin_class
specifier|public
class|class
name|X509TokenBuilder
implements|implements
name|AssertionBuilder
argument_list|<
name|Element
argument_list|>
block|{
name|PolicyBuilder
name|builder
decl_stmt|;
specifier|public
name|X509TokenBuilder
parameter_list|(
name|PolicyBuilder
name|b
parameter_list|)
block|{
name|builder
operator|=
name|b
expr_stmt|;
block|}
specifier|public
name|Assertion
name|build
parameter_list|(
name|Element
name|element
parameter_list|,
name|AssertionBuilderFactory
name|factory
parameter_list|)
throws|throws
name|IllegalArgumentException
block|{
name|SPConstants
name|consts
init|=
name|SP11Constants
operator|.
name|SP_NS
operator|.
name|equals
argument_list|(
name|element
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
condition|?
name|SP11Constants
operator|.
name|INSTANCE
else|:
name|SP12Constants
operator|.
name|INSTANCE
decl_stmt|;
name|X509Token
name|x509Token
init|=
operator|new
name|X509Token
argument_list|(
name|consts
argument_list|)
decl_stmt|;
name|x509Token
operator|.
name|setOptional
argument_list|(
name|PolicyConstants
operator|.
name|isOptional
argument_list|(
name|element
argument_list|)
argument_list|)
expr_stmt|;
name|x509Token
operator|.
name|setIgnorable
argument_list|(
name|PolicyConstants
operator|.
name|isIgnorable
argument_list|(
name|element
argument_list|)
argument_list|)
expr_stmt|;
name|Element
name|policyElement
init|=
name|DOMUtils
operator|.
name|getFirstElement
argument_list|(
name|element
argument_list|)
decl_stmt|;
if|if
condition|(
name|policyElement
operator|==
literal|null
operator|&&
name|consts
operator|!=
name|SP11Constants
operator|.
name|INSTANCE
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"sp:X509Token/wsp:Policy must have a value"
argument_list|)
throw|;
block|}
comment|// Process token inclusion
name|String
name|includeAttr
init|=
name|DOMUtils
operator|.
name|getAttribute
argument_list|(
name|element
argument_list|,
name|consts
operator|.
name|getIncludeToken
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|includeAttr
operator|!=
literal|null
condition|)
block|{
name|SPConstants
operator|.
name|IncludeTokenType
name|inclusion
init|=
name|consts
operator|.
name|getInclusionFromAttributeValue
argument_list|(
name|includeAttr
argument_list|)
decl_stmt|;
name|x509Token
operator|.
name|setInclusion
argument_list|(
name|inclusion
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|policyElement
operator|!=
literal|null
condition|)
block|{
if|if
condition|(
name|DOMUtils
operator|.
name|getFirstChildWithName
argument_list|(
name|policyElement
argument_list|,
name|consts
operator|.
name|getRequiredDerivedKeys
argument_list|()
argument_list|)
operator|!=
literal|null
condition|)
block|{
name|x509Token
operator|.
name|setDerivedKeys
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|DOMUtils
operator|.
name|getFirstChildWithName
argument_list|(
name|policyElement
argument_list|,
name|SP12Constants
operator|.
name|REQUIRE_IMPLIED_DERIVED_KEYS
argument_list|)
operator|!=
literal|null
condition|)
block|{
name|x509Token
operator|.
name|setImpliedDerivedKeys
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|DOMUtils
operator|.
name|getFirstChildWithName
argument_list|(
name|policyElement
argument_list|,
name|SP12Constants
operator|.
name|REQUIRE_EXPLICIT_DERIVED_KEYS
argument_list|)
operator|!=
literal|null
condition|)
block|{
name|x509Token
operator|.
name|setExplicitDerivedKeys
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
block|}
name|Policy
name|policy
init|=
name|builder
operator|.
name|getPolicy
argument_list|(
name|DOMUtils
operator|.
name|getFirstElement
argument_list|(
name|element
argument_list|)
argument_list|)
decl_stmt|;
name|policy
operator|=
name|policy
operator|.
name|normalize
argument_list|(
name|builder
operator|.
name|getPolicyRegistry
argument_list|()
argument_list|,
literal|false
argument_list|)
expr_stmt|;
for|for
control|(
name|Iterator
argument_list|<
name|List
argument_list|<
name|Assertion
argument_list|>
argument_list|>
name|iterator
init|=
name|policy
operator|.
name|getAlternatives
argument_list|()
init|;
name|iterator
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|processAlternative
argument_list|(
name|iterator
operator|.
name|next
argument_list|()
argument_list|,
name|x509Token
argument_list|,
name|consts
argument_list|)
expr_stmt|;
comment|/*              * since there should be only one alternative              */
break|break;
block|}
return|return
name|x509Token
return|;
block|}
specifier|private
name|void
name|processAlternative
parameter_list|(
name|List
argument_list|<
name|Assertion
argument_list|>
name|assertions
parameter_list|,
name|X509Token
name|parent
parameter_list|,
name|SPConstants
name|consts
parameter_list|)
block|{
name|QName
name|name
decl_stmt|;
for|for
control|(
name|Assertion
name|assertion
range|:
name|assertions
control|)
block|{
name|name
operator|=
name|assertion
operator|.
name|getName
argument_list|()
expr_stmt|;
if|if
condition|(
operator|!
name|consts
operator|.
name|getNamespace
argument_list|()
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|SPConstants
operator|.
name|REQUIRE_KEY_IDENTIFIER_REFERENCE
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setRequireKeyIdentifierReference
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|REQUIRE_ISSUER_SERIAL_REFERENCE
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setRequireIssuerSerialReference
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|REQUIRE_EMBEDDED_TOKEN_REFERENCE
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setRequireEmbeddedTokenReference
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|REQUIRE_THUMBPRINT_REFERENCE
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setRequireThumbprintReference
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_V1_TOKEN10
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_V1_TOKEN10
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_V1_TOKEN11
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_V1_TOKEN11
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_V3_TOKEN10
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_V3_TOKEN10
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_V3_TOKEN11
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_V3_TOKEN11
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_PKCS7_TOKEN10
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_PKCS7_TOKEN10
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_PKCS7_TOKEN11
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_PKCS7_TOKEN11
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_PKI_PATH_V1_TOKEN10
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_PKI_PATH_V1_TOKEN10
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|SPConstants
operator|.
name|WSS_X509_PKI_PATH_V1_TOKEN11
operator|.
name|equals
argument_list|(
name|name
operator|.
name|getLocalPart
argument_list|()
argument_list|)
condition|)
block|{
name|parent
operator|.
name|setTokenVersionAndType
argument_list|(
name|SPConstants
operator|.
name|WSS_X509_PKI_PATH_V1_TOKEN11
argument_list|)
expr_stmt|;
block|}
block|}
block|}
specifier|public
name|QName
index|[]
name|getKnownElements
parameter_list|()
block|{
return|return
operator|new
name|QName
index|[]
block|{
name|SP11Constants
operator|.
name|X509_TOKEN
block|,
name|SP12Constants
operator|.
name|X509_TOKEN
block|}
return|;
block|}
block|}
end_class

end_unit

