begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rs
operator|.
name|security
operator|.
name|jose
operator|.
name|jwe
package|;
end_package

begin_import
import|import
name|java
operator|.
name|security
operator|.
name|spec
operator|.
name|AlgorithmParameterSpec
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|logging
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|logging
operator|.
name|LogUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rs
operator|.
name|security
operator|.
name|jose
operator|.
name|jwa
operator|.
name|ContentAlgorithm
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rt
operator|.
name|security
operator|.
name|crypto
operator|.
name|CryptoUtils
import|;
end_import

begin_class
specifier|public
specifier|abstract
class|class
name|AbstractContentEncryptionCipherProperties
implements|implements
name|ContentEncryptionCipherProperties
block|{
specifier|protected
specifier|static
specifier|final
name|Logger
name|LOG
init|=
name|LogUtils
operator|.
name|getL7dLogger
argument_list|(
name|AbstractContentEncryptionCipherProperties
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|int
name|DEFAULT_AUTH_TAG_LENGTH
init|=
literal|128
decl_stmt|;
specifier|private
specifier|final
name|int
name|authTagLen
init|=
name|DEFAULT_AUTH_TAG_LENGTH
decl_stmt|;
specifier|private
specifier|final
name|ContentAlgorithm
name|algo
decl_stmt|;
specifier|public
name|AbstractContentEncryptionCipherProperties
parameter_list|(
name|ContentAlgorithm
name|algo
parameter_list|)
block|{
name|this
operator|.
name|algo
operator|=
name|algo
expr_stmt|;
block|}
specifier|public
name|AlgorithmParameterSpec
name|getAlgorithmParameterSpec
parameter_list|(
name|byte
index|[]
name|theIv
parameter_list|)
block|{
return|return
name|CryptoUtils
operator|.
name|getContentEncryptionCipherSpec
argument_list|(
name|getAuthTagLen
argument_list|()
argument_list|,
name|theIv
argument_list|)
return|;
block|}
specifier|public
name|byte
index|[]
name|getAdditionalAuthenticationData
parameter_list|(
name|String
name|headersJson
parameter_list|,
name|byte
index|[]
name|aad
parameter_list|)
block|{
return|return
name|JweUtils
operator|.
name|getAdditionalAuthenticationData
argument_list|(
name|headersJson
argument_list|,
name|aad
argument_list|)
return|;
block|}
specifier|protected
name|int
name|getAuthTagLen
parameter_list|()
block|{
return|return
name|authTagLen
return|;
block|}
annotation|@
name|Override
specifier|public
name|ContentAlgorithm
name|getAlgorithm
parameter_list|()
block|{
return|return
name|algo
return|;
block|}
block|}
end_class

end_unit

