begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|rs
operator|.
name|security
operator|.
name|jose
operator|.
name|jwe
package|;
end_package

begin_class
specifier|public
class|class
name|JweDecryptionInput
block|{
specifier|private
specifier|final
name|String
name|headersJson
decl_stmt|;
specifier|private
specifier|final
name|byte
index|[]
name|encryptedCEK
decl_stmt|;
specifier|private
specifier|final
name|byte
index|[]
name|initVector
decl_stmt|;
specifier|private
specifier|final
name|byte
index|[]
name|encryptedContent
decl_stmt|;
specifier|private
specifier|final
name|byte
index|[]
name|authTag
decl_stmt|;
specifier|private
specifier|final
name|byte
index|[]
name|aad
decl_stmt|;
specifier|private
specifier|final
name|JweHeaders
name|jweHeaders
decl_stmt|;
specifier|public
name|JweDecryptionInput
parameter_list|(
name|byte
index|[]
name|encryptedCEK
parameter_list|,
name|byte
index|[]
name|initVector
parameter_list|,
name|byte
index|[]
name|encryptedContent
parameter_list|,
name|byte
index|[]
name|authTag
parameter_list|,
name|byte
index|[]
name|aad
parameter_list|,
name|String
name|headersJson
parameter_list|,
name|JweHeaders
name|jweHeaders
parameter_list|)
block|{
name|this
operator|.
name|encryptedCEK
operator|=
name|encryptedCEK
expr_stmt|;
name|this
operator|.
name|initVector
operator|=
name|initVector
expr_stmt|;
name|this
operator|.
name|encryptedContent
operator|=
name|encryptedContent
expr_stmt|;
name|this
operator|.
name|aad
operator|=
name|aad
expr_stmt|;
name|this
operator|.
name|authTag
operator|=
name|authTag
expr_stmt|;
name|this
operator|.
name|headersJson
operator|=
name|headersJson
expr_stmt|;
name|this
operator|.
name|jweHeaders
operator|=
name|jweHeaders
expr_stmt|;
block|}
specifier|public
name|byte
index|[]
name|getEncryptedCEK
parameter_list|()
block|{
return|return
name|encryptedCEK
return|;
block|}
specifier|public
name|byte
index|[]
name|getInitVector
parameter_list|()
block|{
return|return
name|initVector
return|;
block|}
specifier|public
name|byte
index|[]
name|getEncryptedContent
parameter_list|()
block|{
return|return
name|encryptedContent
return|;
block|}
specifier|public
name|byte
index|[]
name|getAuthTag
parameter_list|()
block|{
return|return
name|authTag
return|;
block|}
specifier|public
name|byte
index|[]
name|getAad
parameter_list|()
block|{
return|return
name|aad
return|;
block|}
specifier|public
name|String
name|getDecodedJsonHeaders
parameter_list|()
block|{
return|return
name|headersJson
return|;
block|}
specifier|public
name|JweHeaders
name|getJweHeaders
parameter_list|()
block|{
return|return
name|jweHeaders
return|;
block|}
block|}
end_class

end_unit

