begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ext
operator|.
name|logging
operator|.
name|event
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|LogEvent
block|{
specifier|public
specifier|static
specifier|final
name|String
name|KEY_EXCHANGE_ID
init|=
literal|"exchangeId"
decl_stmt|;
specifier|private
name|String
name|messageId
decl_stmt|;
specifier|private
name|String
name|exchangeId
decl_stmt|;
specifier|private
name|EventType
name|type
decl_stmt|;
specifier|private
name|String
name|address
decl_stmt|;
specifier|private
name|String
name|contentType
decl_stmt|;
specifier|private
name|String
name|encoding
decl_stmt|;
specifier|private
name|String
name|httpMethod
decl_stmt|;
specifier|private
name|String
name|responseCode
decl_stmt|;
specifier|private
name|String
name|principal
decl_stmt|;
specifier|private
name|QName
name|serviceName
decl_stmt|;
comment|// Only for SOAP
specifier|private
name|QName
name|portName
decl_stmt|;
specifier|private
name|QName
name|portTypeName
decl_stmt|;
specifier|private
name|String
name|operationName
decl_stmt|;
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|headers
decl_stmt|;
specifier|private
name|boolean
name|binaryContent
decl_stmt|;
specifier|private
name|String
name|payload
decl_stmt|;
specifier|private
name|boolean
name|truncated
decl_stmt|;
specifier|private
name|File
name|fullContentFile
decl_stmt|;
specifier|public
name|LogEvent
parameter_list|()
block|{     }
specifier|public
name|String
name|getMessageId
parameter_list|()
block|{
return|return
name|messageId
return|;
block|}
specifier|public
name|void
name|setMessageId
parameter_list|(
name|String
name|id
parameter_list|)
block|{
name|this
operator|.
name|messageId
operator|=
name|id
expr_stmt|;
block|}
specifier|public
name|String
name|getExchangeId
parameter_list|()
block|{
return|return
name|exchangeId
return|;
block|}
specifier|public
name|void
name|setExchangeId
parameter_list|(
name|String
name|exchangeId
parameter_list|)
block|{
name|this
operator|.
name|exchangeId
operator|=
name|exchangeId
expr_stmt|;
block|}
specifier|public
name|EventType
name|getType
parameter_list|()
block|{
return|return
name|type
return|;
block|}
specifier|public
name|void
name|setType
parameter_list|(
name|EventType
name|type
parameter_list|)
block|{
name|this
operator|.
name|type
operator|=
name|type
expr_stmt|;
block|}
specifier|public
name|String
name|getAddress
parameter_list|()
block|{
return|return
name|address
return|;
block|}
specifier|public
name|void
name|setAddress
parameter_list|(
name|String
name|address
parameter_list|)
block|{
name|this
operator|.
name|address
operator|=
name|address
expr_stmt|;
block|}
specifier|public
name|String
name|getContentType
parameter_list|()
block|{
return|return
name|contentType
return|;
block|}
specifier|public
name|void
name|setContentType
parameter_list|(
name|String
name|contentType
parameter_list|)
block|{
name|this
operator|.
name|contentType
operator|=
name|contentType
expr_stmt|;
block|}
specifier|public
name|String
name|getEncoding
parameter_list|()
block|{
return|return
name|encoding
return|;
block|}
specifier|public
name|void
name|setEncoding
parameter_list|(
name|String
name|encoding
parameter_list|)
block|{
name|this
operator|.
name|encoding
operator|=
name|encoding
expr_stmt|;
block|}
specifier|public
name|String
name|getHttpMethod
parameter_list|()
block|{
return|return
name|httpMethod
return|;
block|}
specifier|public
name|void
name|setHttpMethod
parameter_list|(
name|String
name|httpMethod
parameter_list|)
block|{
name|this
operator|.
name|httpMethod
operator|=
name|httpMethod
expr_stmt|;
block|}
specifier|public
name|String
name|getResponseCode
parameter_list|()
block|{
return|return
name|responseCode
return|;
block|}
specifier|public
name|void
name|setResponseCode
parameter_list|(
name|String
name|responseCode
parameter_list|)
block|{
name|this
operator|.
name|responseCode
operator|=
name|responseCode
expr_stmt|;
block|}
specifier|public
name|String
name|getPrincipal
parameter_list|()
block|{
return|return
name|principal
return|;
block|}
specifier|public
name|void
name|setPrincipal
parameter_list|(
name|String
name|principal
parameter_list|)
block|{
name|this
operator|.
name|principal
operator|=
name|principal
expr_stmt|;
block|}
specifier|public
name|QName
name|getServiceName
parameter_list|()
block|{
return|return
name|serviceName
return|;
block|}
specifier|public
name|void
name|setServiceName
parameter_list|(
name|QName
name|serviceName
parameter_list|)
block|{
name|this
operator|.
name|serviceName
operator|=
name|serviceName
expr_stmt|;
block|}
specifier|public
name|QName
name|getPortName
parameter_list|()
block|{
return|return
name|portName
return|;
block|}
specifier|public
name|void
name|setPortName
parameter_list|(
name|QName
name|portName
parameter_list|)
block|{
name|this
operator|.
name|portName
operator|=
name|portName
expr_stmt|;
block|}
specifier|public
name|QName
name|getPortTypeName
parameter_list|()
block|{
return|return
name|portTypeName
return|;
block|}
specifier|public
name|void
name|setPortTypeName
parameter_list|(
name|QName
name|portTypeName
parameter_list|)
block|{
name|this
operator|.
name|portTypeName
operator|=
name|portTypeName
expr_stmt|;
block|}
specifier|public
name|String
name|getOperationName
parameter_list|()
block|{
return|return
name|operationName
return|;
block|}
specifier|public
name|void
name|setOperationName
parameter_list|(
name|String
name|operationName
parameter_list|)
block|{
name|this
operator|.
name|operationName
operator|=
name|operationName
expr_stmt|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|getHeaders
parameter_list|()
block|{
return|return
name|headers
return|;
block|}
specifier|public
name|void
name|setHeaders
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|headers
parameter_list|)
block|{
name|this
operator|.
name|headers
operator|=
name|headers
expr_stmt|;
block|}
specifier|public
name|boolean
name|isBinaryContent
parameter_list|()
block|{
return|return
name|binaryContent
return|;
block|}
specifier|public
name|void
name|setBinaryContent
parameter_list|(
name|boolean
name|binaryContent
parameter_list|)
block|{
name|this
operator|.
name|binaryContent
operator|=
name|binaryContent
expr_stmt|;
block|}
specifier|public
name|String
name|getPayload
parameter_list|()
block|{
return|return
name|payload
return|;
block|}
specifier|public
name|void
name|setPayload
parameter_list|(
name|String
name|payload
parameter_list|)
block|{
name|this
operator|.
name|payload
operator|=
name|payload
expr_stmt|;
block|}
specifier|public
name|boolean
name|isTruncated
parameter_list|()
block|{
return|return
name|truncated
return|;
block|}
specifier|public
name|void
name|setTruncated
parameter_list|(
name|boolean
name|truncated
parameter_list|)
block|{
name|this
operator|.
name|truncated
operator|=
name|truncated
expr_stmt|;
block|}
specifier|public
name|File
name|getFullContentFile
parameter_list|()
block|{
return|return
name|fullContentFile
return|;
block|}
specifier|public
name|void
name|setFullContentFile
parameter_list|(
name|File
name|fullContentFile
parameter_list|)
block|{
name|this
operator|.
name|fullContentFile
operator|=
name|fullContentFile
expr_stmt|;
block|}
block|}
end_class

end_unit

