begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|addressing
package|;
end_package

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|AddressingBuilderImplTest
extends|extends
name|Assert
block|{
specifier|private
name|AddressingBuilderImpl
name|builder
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|setUp
parameter_list|()
block|{
name|builder
operator|=
operator|new
name|AddressingBuilderImpl
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testGetAddressingProperties
parameter_list|()
throws|throws
name|Exception
block|{
name|AddressingProperties
name|properties
init|=
name|builder
operator|.
name|newAddressingProperties
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"expected AddressingProperties "
argument_list|,
name|properties
argument_list|)
expr_stmt|;
name|assertNotSame
argument_list|(
literal|"unexpected same properties"
argument_list|,
name|builder
operator|.
name|newAddressingProperties
argument_list|()
argument_list|,
name|properties
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testGetAddressingConstants
parameter_list|()
throws|throws
name|Exception
block|{
name|AddressingConstants
name|constants
init|=
name|builder
operator|.
name|newAddressingConstants
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"expected AddressingConstants "
argument_list|,
name|constants
argument_list|)
expr_stmt|;
name|assertNotSame
argument_list|(
literal|"unexpected same constants"
argument_list|,
name|builder
operator|.
name|newAddressingConstants
argument_list|()
argument_list|,
name|constants
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

