begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|systest
operator|.
name|jms
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|Binding
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|Endpoint
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|ws
operator|.
name|soap
operator|.
name|SOAPBinding
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxws
operator|.
name|EndpointImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxws
operator|.
name|JaxWsServerFactoryBean
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|testutil
operator|.
name|common
operator|.
name|AbstractBusTestServerBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|jms
operator|.
name|spec
operator|.
name|JMSSpecConstants
import|;
end_import

begin_class
specifier|public
class|class
name|Server
extends|extends
name|AbstractBusTestServerBase
block|{
specifier|protected
name|void
name|run
parameter_list|()
block|{
name|Object
name|implementor
init|=
operator|new
name|GreeterImplTwoWayJMS
argument_list|()
decl_stmt|;
name|Object
name|impl2
init|=
operator|new
name|GreeterImplQueueOneWay
argument_list|()
decl_stmt|;
name|Object
name|impl3
init|=
operator|new
name|GreeterImplTopicOneWay
argument_list|()
decl_stmt|;
name|Object
name|impleDoc
init|=
operator|new
name|GreeterImplDoc
argument_list|()
decl_stmt|;
name|Object
name|impl4
init|=
operator|new
name|GreeterByteMessageImpl
argument_list|()
decl_stmt|;
name|Object
name|impl5
init|=
operator|new
name|SoapService6SoapPort6Impl
argument_list|()
decl_stmt|;
name|Object
name|impl6
init|=
operator|new
name|JmsDestPubSubImpl
argument_list|()
decl_stmt|;
name|Object
name|i1
init|=
operator|new
name|GreeterImplTwoWayJMSAppCorrelationIDNoPrefix
argument_list|()
decl_stmt|;
name|Object
name|i2
init|=
operator|new
name|GreeterImplTwoWayJMSAppCorrelationIDStaticPrefixEng
argument_list|()
decl_stmt|;
name|Object
name|i3
init|=
operator|new
name|GreeterImplTwoWayJMSAppCorrelationIDStaticPrefixSales
argument_list|()
decl_stmt|;
name|Object
name|i4
init|=
operator|new
name|GreeterImplTwoWayJMSRuntimeCorrelationIDDynamicPrefix
argument_list|()
decl_stmt|;
name|Object
name|i5
init|=
operator|new
name|GreeterImplTwoWayJMSRuntimeCorrelationIDStaticPrefixEng
argument_list|()
decl_stmt|;
name|Object
name|i6
init|=
operator|new
name|GreeterImplTwoWayJMSRuntimeCorrelationIDStaticPrefixSales
argument_list|()
decl_stmt|;
name|Object
name|i7
init|=
operator|new
name|GreeterImplTwoWayJMSAppCorrelationIDEng
argument_list|()
decl_stmt|;
name|Object
name|i8
init|=
operator|new
name|GreeterImplTwoWayJMSAppCorrelationIDSales
argument_list|()
decl_stmt|;
name|Object
name|mtom
init|=
operator|new
name|JMSMTOMImpl
argument_list|()
decl_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|null
argument_list|,
name|impleDoc
argument_list|)
expr_stmt|;
name|String
name|address
init|=
literal|"http://localhost:9000/SoapContext/SoapPort"
decl_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
name|address
argument_list|,
name|implementor
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://testaddr.not.required/"
argument_list|,
name|impl2
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://testaddr.not.required.topic/"
argument_list|,
name|impl3
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://testaddr.not.required.byte/"
argument_list|,
name|impl4
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://testaddr.not.required.jms/"
argument_list|,
name|impl5
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://ignore"
argument_list|,
name|impl6
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i1
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i2
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i3
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i4
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i5
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i6
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i7
argument_list|)
expr_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
literal|""
argument_list|,
name|i8
argument_list|)
expr_stmt|;
name|EndpointImpl
name|ep
init|=
operator|(
name|EndpointImpl
operator|)
name|Endpoint
operator|.
name|publish
argument_list|(
literal|"http://cxf.apache.org/transports/jms"
argument_list|,
name|mtom
argument_list|)
decl_stmt|;
name|Binding
name|binding
init|=
name|ep
operator|.
name|getBinding
argument_list|()
decl_stmt|;
operator|(
operator|(
name|SOAPBinding
operator|)
name|binding
operator|)
operator|.
name|setMTOMEnabled
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|Object
name|spec1
init|=
operator|new
name|GreeterSpecImpl
argument_list|()
decl_stmt|;
name|String
name|address1
init|=
literal|"jms:jndi:dynamicQueues/test.cxf.jmstransport.queue2"
operator|+
literal|"?jndiInitialContextFactory"
operator|+
literal|"=org.apache.activemq.jndi.ActiveMQInitialContextFactory"
operator|+
literal|"&jndiConnectionFactoryName=ConnectionFactory&jndiURL=tcp://localhost:61500"
decl_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
name|address1
argument_list|,
name|spec1
argument_list|)
expr_stmt|;
name|Object
name|spec2
init|=
operator|new
name|GreeterSpecWithPortError
argument_list|()
decl_stmt|;
name|String
name|address2
init|=
literal|"jms:jndi:dynamicQueues/test.cxf.jmstransport.queue5"
operator|+
literal|"?jndiInitialContextFactory"
operator|+
literal|"=org.apache.activemq.jndi.ActiveMQInitialContextFactory"
operator|+
literal|"&jndiConnectionFactoryName=ConnectionFactory&jndiURL=tcp://localhost:61500"
decl_stmt|;
name|Endpoint
operator|.
name|publish
argument_list|(
name|address2
argument_list|,
name|spec2
argument_list|)
expr_stmt|;
name|initNoWsdlServer
argument_list|()
expr_stmt|;
block|}
comment|/**      *       */
specifier|private
name|void
name|initNoWsdlServer
parameter_list|()
block|{
name|String
name|address
init|=
literal|"jms:jndi:dynamicQueues/test.cxf.jmstransport.queue3"
operator|+
literal|"?jndiInitialContextFactory"
operator|+
literal|"=org.apache.activemq.jndi.ActiveMQInitialContextFactory"
operator|+
literal|"&jndiConnectionFactoryName=ConnectionFactory&jndiURL=tcp://localhost:61500"
decl_stmt|;
name|Hello
name|implementor
init|=
operator|new
name|HelloImpl
argument_list|()
decl_stmt|;
name|JaxWsServerFactoryBean
name|svrFactory
init|=
operator|new
name|JaxWsServerFactoryBean
argument_list|()
decl_stmt|;
name|svrFactory
operator|.
name|setServiceClass
argument_list|(
name|Hello
operator|.
name|class
argument_list|)
expr_stmt|;
name|svrFactory
operator|.
name|setAddress
argument_list|(
name|address
argument_list|)
expr_stmt|;
name|svrFactory
operator|.
name|setTransportId
argument_list|(
name|JMSSpecConstants
operator|.
name|SOAP_JMS_SPECIFICIATION_TRANSPORTID
argument_list|)
expr_stmt|;
name|svrFactory
operator|.
name|setServiceBean
argument_list|(
name|implementor
argument_list|)
expr_stmt|;
name|svrFactory
operator|.
name|create
argument_list|()
expr_stmt|;
block|}
specifier|public
specifier|static
name|void
name|main
parameter_list|(
name|String
index|[]
name|args
parameter_list|)
block|{
try|try
block|{
name|Server
name|s
init|=
operator|new
name|Server
argument_list|()
decl_stmt|;
name|s
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
name|ex
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
name|System
operator|.
name|exit
argument_list|(
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
finally|finally
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"done!"
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

