begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|GET
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlRootElement
import|;
end_import

begin_class
annotation|@
name|XmlRootElement
argument_list|(
name|name
operator|=
literal|"Book"
argument_list|)
specifier|public
class|class
name|Book
implements|implements
name|Comparable
argument_list|<
name|Book
argument_list|>
block|{
specifier|private
name|String
name|name
decl_stmt|;
specifier|private
name|long
name|id
decl_stmt|;
specifier|public
name|Book
parameter_list|()
block|{     }
specifier|public
name|Book
parameter_list|(
name|String
name|name
parameter_list|,
name|long
name|id
parameter_list|)
block|{
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
name|this
operator|.
name|id
operator|=
name|id
expr_stmt|;
block|}
specifier|public
name|void
name|setName
parameter_list|(
name|String
name|n
parameter_list|)
block|{
name|name
operator|=
name|n
expr_stmt|;
block|}
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|name
return|;
block|}
specifier|public
name|void
name|setId
parameter_list|(
name|long
name|i
parameter_list|)
block|{
name|id
operator|=
name|i
expr_stmt|;
block|}
specifier|public
name|long
name|getId
parameter_list|()
block|{
return|return
name|id
return|;
block|}
annotation|@
name|GET
specifier|public
name|String
name|getState
parameter_list|()
block|{
return|return
literal|""
return|;
block|}
specifier|public
name|void
name|setState
parameter_list|(
name|String
name|s
parameter_list|)
block|{     }
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
return|return
name|name
operator|.
name|hashCode
argument_list|()
operator|*
literal|37
operator|+
operator|new
name|Long
argument_list|(
name|id
argument_list|)
operator|.
name|hashCode
argument_list|()
return|;
block|}
specifier|public
name|boolean
name|equals
parameter_list|(
name|Object
name|o
parameter_list|)
block|{
if|if
condition|(
operator|!
operator|(
name|o
operator|instanceof
name|Book
operator|)
condition|)
block|{
return|return
literal|false
return|;
block|}
name|Book
name|other
init|=
operator|(
name|Book
operator|)
name|o
decl_stmt|;
return|return
name|other
operator|.
name|name
operator|.
name|equals
argument_list|(
name|name
argument_list|)
operator|&&
name|other
operator|.
name|id
operator|==
name|id
return|;
block|}
specifier|public
name|int
name|compareTo
parameter_list|(
name|Book
name|b
parameter_list|)
block|{
name|Long
name|i1
init|=
operator|new
name|Long
argument_list|(
name|getId
argument_list|()
argument_list|)
decl_stmt|;
name|Long
name|i2
init|=
operator|new
name|Long
argument_list|(
name|b
operator|.
name|getId
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|i1
operator|.
name|compareTo
argument_list|(
name|i2
argument_list|)
return|;
block|}
block|}
end_class

end_unit

