begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|corba
operator|.
name|common
operator|.
name|idltypes
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|PrintWriter
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|IdlInterface
extends|extends
name|IdlScopeBase
implements|implements
name|IdlType
block|{
specifier|private
name|IdlInterface
parameter_list|(
name|IdlScopeBase
name|parent
parameter_list|,
name|String
name|name
parameter_list|)
block|{
name|super
argument_list|(
name|parent
argument_list|,
name|name
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
name|IdlInterface
name|create
parameter_list|(
name|IdlScopeBase
name|parent
parameter_list|,
name|String
name|name
parameter_list|)
block|{
return|return
operator|new
name|IdlInterface
argument_list|(
name|parent
argument_list|,
name|name
argument_list|)
return|;
block|}
specifier|public
name|void
name|addoperation
parameter_list|(
name|IdlOperation
name|op
parameter_list|)
block|{
name|addToScope
argument_list|(
name|op
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|addAttribute
parameter_list|(
name|IdlAttribute
name|attr
parameter_list|)
block|{
name|addToScope
argument_list|(
name|attr
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|write
parameter_list|(
name|PrintWriter
name|pw
parameter_list|)
block|{
name|pw
operator|.
name|println
argument_list|(
name|indent
argument_list|()
operator|+
literal|"interface "
operator|+
name|localName
argument_list|()
operator|+
literal|" {"
argument_list|)
expr_stmt|;
name|indentMore
argument_list|()
expr_stmt|;
name|super
operator|.
name|write
argument_list|(
name|pw
argument_list|)
expr_stmt|;
name|indentLess
argument_list|()
expr_stmt|;
name|pw
operator|.
name|println
argument_list|(
name|indent
argument_list|()
operator|+
literal|"};"
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

