begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|corba
operator|.
name|common
operator|.
name|idltypes
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|PrintWriter
import|;
end_import

begin_class
specifier|public
specifier|final
class|class
name|IdlTypedef
extends|extends
name|IdlDefnImplBase
implements|implements
name|IdlType
block|{
specifier|private
name|IdlType
name|base
decl_stmt|;
specifier|private
name|IdlTypedef
parameter_list|(
name|IdlScopeBase
name|parent
parameter_list|,
name|String
name|name
parameter_list|,
name|IdlType
name|basetype
parameter_list|)
block|{
name|super
argument_list|(
name|parent
argument_list|,
name|name
argument_list|)
expr_stmt|;
name|this
operator|.
name|base
operator|=
name|basetype
expr_stmt|;
block|}
specifier|public
specifier|static
name|IdlTypedef
name|create
parameter_list|(
name|IdlScopeBase
name|parent
parameter_list|,
name|String
name|name
parameter_list|,
name|IdlType
name|base
parameter_list|)
block|{
return|return
operator|new
name|IdlTypedef
argument_list|(
name|parent
argument_list|,
name|name
argument_list|,
name|base
argument_list|)
return|;
block|}
name|IdlType
name|baseType
parameter_list|()
block|{
return|return
name|base
return|;
block|}
specifier|public
name|void
name|write
parameter_list|(
name|PrintWriter
name|pw
parameter_list|)
block|{
name|pw
operator|.
name|println
argument_list|(
name|indent
argument_list|()
operator|+
literal|"typedef "
operator|+
name|base
operator|.
name|fullName
argument_list|(
name|scopeName
argument_list|()
argument_list|)
operator|+
literal|" "
operator|+
name|localName
argument_list|()
operator|+
literal|";"
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

