begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
operator|.
name|jpa
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
operator|.
name|SearchCondition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|ext
operator|.
name|search
operator|.
name|fiql
operator|.
name|FiqlParser
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_class
specifier|public
class|class
name|JPALanguageVisitorTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testSimpleQuery
parameter_list|()
throws|throws
name|Exception
block|{
name|SearchCondition
argument_list|<
name|Book
argument_list|>
name|filter
init|=
operator|new
name|FiqlParser
argument_list|<>
argument_list|(
name|Book
operator|.
name|class
argument_list|)
operator|.
name|parse
argument_list|(
literal|"id=lt=10"
argument_list|)
decl_stmt|;
name|JPALanguageVisitor
argument_list|<
name|Book
argument_list|>
name|jpa
init|=
operator|new
name|JPALanguageVisitor
argument_list|<>
argument_list|(
name|Book
operator|.
name|class
argument_list|)
decl_stmt|;
name|filter
operator|.
name|accept
argument_list|(
name|jpa
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"SELECT t FROM Book t WHERE t.id< '10'"
argument_list|,
name|jpa
operator|.
name|getQuery
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

