begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|aegis
operator|.
name|type
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|Bus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|endpoint
operator|.
name|Server
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|test
operator|.
name|AbstractCXFSpringTest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|test
operator|.
name|TestUtilities
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|testutil
operator|.
name|common
operator|.
name|TestUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_comment
comment|/**  *   */
end_comment

begin_class
specifier|public
class|class
name|TypeCreationOptionsSpringTest
extends|extends
name|AbstractCXFSpringTest
block|{
specifier|public
specifier|static
specifier|final
name|String
name|PORT
init|=
name|TestUtil
operator|.
name|getPortNumber
argument_list|(
name|TypeCreationOptionsSpringTest
operator|.
name|class
argument_list|)
decl_stmt|;
annotation|@
name|Override
specifier|protected
name|String
index|[]
name|getConfigLocations
parameter_list|()
block|{
name|setConfigContextClass
argument_list|(
name|TypeCreationOptionsSpringTest
operator|.
name|class
argument_list|)
expr_stmt|;
return|return
operator|new
name|String
index|[]
block|{
literal|"/org/apache/cxf/aegis/type/aegisOptionsTestBeans.xml"
block|}
return|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testMinOccurs
parameter_list|()
throws|throws
name|Exception
block|{
name|TestUtilities
name|testUtilities
init|=
operator|new
name|TestUtilities
argument_list|(
name|TypeCreationOptionsSpringTest
operator|.
name|class
argument_list|)
decl_stmt|;
name|testUtilities
operator|.
name|setBus
argument_list|(
name|getBean
argument_list|(
name|Bus
operator|.
name|class
argument_list|,
literal|"cxf"
argument_list|)
argument_list|)
expr_stmt|;
name|testUtilities
operator|.
name|addDefaultNamespaces
argument_list|()
expr_stmt|;
name|testUtilities
operator|.
name|addNamespace
argument_list|(
literal|"ts"
argument_list|,
literal|"http://cxf.org.apache/service"
argument_list|)
expr_stmt|;
comment|//{urn:org.apache.cxf.aegis}arrayService
name|Server
name|s
init|=
name|testUtilities
operator|.
name|getServerForService
argument_list|(
operator|new
name|QName
argument_list|(
literal|"urn:org.apache.cxf.aegis"
argument_list|,
literal|"arrayService"
argument_list|)
argument_list|)
decl_stmt|;
name|Document
name|wsdl
init|=
name|testUtilities
operator|.
name|getWSDLDocument
argument_list|(
name|s
argument_list|)
decl_stmt|;
name|assertXPathEquals
argument_list|(
literal|"//xsd:complexType[@name='ArrayOfInt']/"
operator|+
literal|"xsd:sequence/xsd:element[@name='int']/@minOccurs"
argument_list|,
literal|"3"
argument_list|,
name|wsdl
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

