begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|javascript
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Stack
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Attr
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|WSDLConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|xmlschema
operator|.
name|SchemaCollection
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|xmlschema
operator|.
name|XmlSchemaConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|common
operator|.
name|xmlschema
operator|.
name|XmlSchemaUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|databinding
operator|.
name|source
operator|.
name|mime
operator|.
name|MimeAttribute
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaComplexType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaElement
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaSimpleContent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaSimpleContentExtension
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaSimpleType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|XmlSchemaType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ws
operator|.
name|commons
operator|.
name|schema
operator|.
name|constants
operator|.
name|Constants
import|;
end_import

begin_comment
comment|/**  * A set of functions that assist in JavaScript generation. This includes  * functions for appending strings of JavaScript to a buffer as well as some  * type utilities.  */
end_comment

begin_class
specifier|public
class|class
name|JavascriptUtils
block|{
specifier|private
specifier|static
specifier|final
name|String
name|NL
init|=
literal|"\n"
decl_stmt|;
specifier|private
specifier|static
name|int
name|anyTypePrefixCounter
decl_stmt|;
specifier|private
name|StringBuilder
name|code
decl_stmt|;
specifier|private
name|Stack
argument_list|<
name|String
argument_list|>
name|prefixStack
decl_stmt|;
specifier|private
name|String
name|xmlStringAccumulatorVariable
decl_stmt|;
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|defaultValueForSimpleType
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|nonStringSimpleTypes
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|intTypes
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|floatTypes
decl_stmt|;
specifier|public
name|JavascriptUtils
parameter_list|(
name|StringBuilder
name|code
parameter_list|)
block|{
name|this
operator|.
name|code
operator|=
name|code
expr_stmt|;
name|defaultValueForSimpleType
operator|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"int"
argument_list|,
literal|"0"
argument_list|)
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"unsignedInt"
argument_list|,
literal|"0"
argument_list|)
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"long"
argument_list|,
literal|"0"
argument_list|)
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"unsignedLong"
argument_list|,
literal|"0"
argument_list|)
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"float"
argument_list|,
literal|"0.0"
argument_list|)
expr_stmt|;
name|defaultValueForSimpleType
operator|.
name|put
argument_list|(
literal|"double"
argument_list|,
literal|"0.0"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"int"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"long"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"unsignedInt"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"unsignedLong"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"float"
argument_list|)
expr_stmt|;
name|nonStringSimpleTypes
operator|.
name|add
argument_list|(
literal|"double"
argument_list|)
expr_stmt|;
name|intTypes
operator|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|intTypes
operator|.
name|add
argument_list|(
literal|"int"
argument_list|)
expr_stmt|;
name|intTypes
operator|.
name|add
argument_list|(
literal|"long"
argument_list|)
expr_stmt|;
name|intTypes
operator|.
name|add
argument_list|(
literal|"unsignedInt"
argument_list|)
expr_stmt|;
name|intTypes
operator|.
name|add
argument_list|(
literal|"unsignedLong"
argument_list|)
expr_stmt|;
name|floatTypes
operator|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|floatTypes
operator|.
name|add
argument_list|(
literal|"float"
argument_list|)
expr_stmt|;
name|floatTypes
operator|.
name|add
argument_list|(
literal|"double"
argument_list|)
expr_stmt|;
name|prefixStack
operator|=
operator|new
name|Stack
argument_list|<
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
literal|"    "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getDefaultValueForSimpleType
parameter_list|(
name|XmlSchemaType
name|type
parameter_list|)
block|{
name|String
name|val
init|=
name|defaultValueForSimpleType
operator|.
name|get
argument_list|(
name|type
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|val
operator|==
literal|null
condition|)
block|{
comment|// ints and such return the appropriate 0.
return|return
literal|"''"
return|;
block|}
else|else
block|{
return|return
name|val
return|;
block|}
block|}
specifier|public
name|boolean
name|isStringSimpleType
parameter_list|(
name|QName
name|typeName
parameter_list|)
block|{
return|return
operator|!
operator|(
name|WSDLConstants
operator|.
name|NS_SCHEMA_XSD
operator|.
name|equals
argument_list|(
name|typeName
operator|.
name|getNamespaceURI
argument_list|()
argument_list|)
operator|&&
name|nonStringSimpleTypes
operator|.
name|contains
argument_list|(
name|typeName
operator|.
name|getLocalPart
argument_list|()
argument_list|)
operator|)
return|;
block|}
specifier|public
name|void
name|setXmlStringAccumulator
parameter_list|(
name|String
name|variableName
parameter_list|)
block|{
name|xmlStringAccumulatorVariable
operator|=
name|variableName
expr_stmt|;
block|}
specifier|public
name|void
name|startXmlStringAccumulator
parameter_list|(
name|String
name|variableName
parameter_list|)
block|{
name|xmlStringAccumulatorVariable
operator|=
name|variableName
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"var "
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|variableName
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|" = '';"
operator|+
name|NL
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
name|String
name|protectSingleQuotes
parameter_list|(
name|String
name|value
parameter_list|)
block|{
return|return
name|value
operator|.
name|replaceAll
argument_list|(
literal|"'"
argument_list|,
literal|"\\'"
argument_list|)
return|;
block|}
specifier|public
name|String
name|escapeStringQuotes
parameter_list|(
name|String
name|data
parameter_list|)
block|{
return|return
name|data
operator|.
name|replace
argument_list|(
literal|"'"
argument_list|,
literal|"\\'"
argument_list|)
return|;
block|}
comment|/**      * emit javascript to append a value to the accumulator.      *       * @param value      */
specifier|public
name|void
name|appendString
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|xmlStringAccumulatorVariable
operator|+
literal|" = "
operator|+
name|xmlStringAccumulatorVariable
operator|+
literal|" + '"
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|escapeStringQuotes
argument_list|(
name|value
argument_list|)
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"';"
operator|+
name|NL
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|appendExpression
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|xmlStringAccumulatorVariable
operator|+
literal|" = "
operator|+
name|xmlStringAccumulatorVariable
operator|+
literal|" + "
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|value
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|";"
operator|+
name|NL
argument_list|)
expr_stmt|;
block|}
specifier|private
name|String
name|prefix
parameter_list|()
block|{
return|return
name|prefixStack
operator|.
name|peek
argument_list|()
return|;
block|}
specifier|public
name|void
name|appendLine
parameter_list|(
name|String
name|line
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|line
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|NL
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startIf
parameter_list|(
name|String
name|test
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"if ("
operator|+
name|test
operator|+
literal|") {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startBlock
parameter_list|()
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"{"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|appendElse
parameter_list|()
block|{
name|prefixStack
operator|.
name|pop
argument_list|()
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"} else {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|endBlock
parameter_list|()
block|{
name|prefixStack
operator|.
name|pop
argument_list|()
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"}"
operator|+
name|NL
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startFor
parameter_list|(
name|String
name|start
parameter_list|,
name|String
name|test
parameter_list|,
name|String
name|increment
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"for ("
operator|+
name|start
operator|+
literal|";"
operator|+
name|test
operator|+
literal|";"
operator|+
name|increment
operator|+
literal|") {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startForIn
parameter_list|(
name|String
name|var
parameter_list|,
name|String
name|collection
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"for (var "
operator|+
name|var
operator|+
literal|" in "
operator|+
name|collection
operator|+
literal|") {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startWhile
parameter_list|(
name|String
name|test
parameter_list|)
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"while ("
operator|+
name|test
operator|+
literal|") {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|startDo
parameter_list|()
block|{
name|code
operator|.
name|append
argument_list|(
name|prefix
argument_list|()
argument_list|)
expr_stmt|;
name|code
operator|.
name|append
argument_list|(
literal|"do  {"
operator|+
name|NL
argument_list|)
expr_stmt|;
name|prefixStack
operator|.
name|push
argument_list|(
name|prefix
argument_list|()
operator|+
literal|" "
argument_list|)
expr_stmt|;
block|}
comment|// Given a js variable and a simple type object, correctly set the variables
comment|// simple type
specifier|public
name|String
name|javascriptParseExpression
parameter_list|(
name|XmlSchemaType
name|type
parameter_list|,
name|String
name|value
parameter_list|)
block|{
if|if
condition|(
operator|!
operator|(
name|type
operator|instanceof
name|XmlSchemaSimpleType
operator|)
condition|)
block|{
return|return
name|value
return|;
block|}
name|String
name|name
init|=
name|type
operator|.
name|getName
argument_list|()
decl_stmt|;
if|if
condition|(
name|intTypes
operator|.
name|contains
argument_list|(
name|name
argument_list|)
condition|)
block|{
return|return
literal|"parseInt("
operator|+
name|value
operator|+
literal|")"
return|;
block|}
elseif|else
if|if
condition|(
name|floatTypes
operator|.
name|contains
argument_list|(
name|name
argument_list|)
condition|)
block|{
return|return
literal|"parseFloat("
operator|+
name|value
operator|+
literal|")"
return|;
block|}
elseif|else
if|if
condition|(
literal|"boolean"
operator|.
name|equals
argument_list|(
name|name
argument_list|)
condition|)
block|{
return|return
literal|"("
operator|+
name|value
operator|+
literal|" == 'true')"
return|;
block|}
else|else
block|{
return|return
name|value
return|;
block|}
block|}
specifier|public
specifier|static
name|String
name|javaScriptNameToken
parameter_list|(
name|String
name|token
parameter_list|)
block|{
return|return
name|token
return|;
block|}
comment|/**      * We really don't want to take the attitude that 'all base64Binary elements are candidates for MTOM'.      * So we look for clues.      * @param schemaObject      * @return      */
specifier|private
name|boolean
name|treatAsMtom
parameter_list|(
name|XmlSchemaObject
name|schemaObject
parameter_list|)
block|{
if|if
condition|(
name|schemaObject
operator|==
literal|null
condition|)
block|{
return|return
literal|false
return|;
block|}
name|Map
name|metaInfoMap
init|=
name|schemaObject
operator|.
name|getMetaInfoMap
argument_list|()
decl_stmt|;
if|if
condition|(
name|metaInfoMap
operator|!=
literal|null
condition|)
block|{
name|Map
name|attribMap
init|=
operator|(
name|Map
operator|)
name|metaInfoMap
operator|.
name|get
argument_list|(
name|Constants
operator|.
name|MetaDataConstants
operator|.
name|EXTERNAL_ATTRIBUTES
argument_list|)
decl_stmt|;
name|Attr
name|ctAttr
init|=
operator|(
name|Attr
operator|)
name|attribMap
operator|.
name|get
argument_list|(
name|MimeAttribute
operator|.
name|MIME_QNAME
argument_list|)
decl_stmt|;
if|if
condition|(
name|ctAttr
operator|!=
literal|null
condition|)
block|{
return|return
literal|true
return|;
block|}
block|}
if|if
condition|(
name|schemaObject
operator|instanceof
name|XmlSchemaElement
condition|)
block|{
name|XmlSchemaElement
name|element
init|=
operator|(
name|XmlSchemaElement
operator|)
name|schemaObject
decl_stmt|;
if|if
condition|(
name|element
operator|.
name|getSchemaType
argument_list|()
operator|==
literal|null
condition|)
block|{
return|return
literal|false
return|;
block|}
name|QName
name|typeName
init|=
name|element
operator|.
name|getSchemaType
argument_list|()
operator|.
name|getQName
argument_list|()
decl_stmt|;
comment|// We could do something much more complex in terms of evaluating whether the type
comment|// permits the contentType attribute. This, however, is enough to clue us in for what Aegis
comment|// does.
if|if
condition|(
operator|new
name|QName
argument_list|(
literal|"http://www.w3.org/2005/05/xmlmime"
argument_list|,
literal|"base64Binary"
argument_list|)
operator|.
name|equals
argument_list|(
name|typeName
argument_list|)
condition|)
block|{
return|return
literal|true
return|;
block|}
block|}
return|return
literal|false
return|;
block|}
comment|/**      * We don't want to generate Javascript overhead for complex types with simple content models,      * at least until or unless we decide to cope with attributes in a general way.      * @param type      * @return      */
specifier|public
specifier|static
name|boolean
name|notVeryComplexType
parameter_list|(
name|XmlSchemaType
name|type
parameter_list|)
block|{
return|return
name|type
operator|instanceof
name|XmlSchemaSimpleType
operator|||
operator|(
name|type
operator|instanceof
name|XmlSchemaComplexType
operator|&&
operator|(
operator|(
name|XmlSchemaComplexType
operator|)
name|type
operator|)
operator|.
name|getContentModel
argument_list|()
operator|instanceof
name|XmlSchemaSimpleContent
operator|)
return|;
block|}
comment|/**      * Return true for xsd:base64Binary or simple restrictions of it, as in the xmime stock type.      * @param type      * @return      */
specifier|public
specifier|static
name|boolean
name|mtomCandidateType
parameter_list|(
name|XmlSchemaType
name|type
parameter_list|)
block|{
if|if
condition|(
name|type
operator|==
literal|null
condition|)
block|{
return|return
literal|false
return|;
block|}
if|if
condition|(
name|XmlSchemaConstants
operator|.
name|BASE64BINARY_QNAME
operator|.
name|equals
argument_list|(
name|type
operator|.
name|getQName
argument_list|()
argument_list|)
condition|)
block|{
return|return
literal|true
return|;
block|}
comment|// there could be some disagreement whether the following is a good enough test.
comment|// what if 'base64binary' was extended in some crazy way? At runtime, either it has
comment|// an xop:Include or it doesn't.
if|if
condition|(
name|type
operator|instanceof
name|XmlSchemaComplexType
condition|)
block|{
name|XmlSchemaComplexType
name|complexType
init|=
operator|(
name|XmlSchemaComplexType
operator|)
name|type
decl_stmt|;
if|if
condition|(
name|complexType
operator|.
name|getContentModel
argument_list|()
operator|instanceof
name|XmlSchemaSimpleContent
condition|)
block|{
name|XmlSchemaSimpleContent
name|content
init|=
operator|(
name|XmlSchemaSimpleContent
operator|)
name|complexType
operator|.
name|getContentModel
argument_list|()
decl_stmt|;
if|if
condition|(
name|content
operator|.
name|getContent
argument_list|()
operator|instanceof
name|XmlSchemaSimpleContentExtension
condition|)
block|{
name|XmlSchemaSimpleContentExtension
name|extension
init|=
operator|(
name|XmlSchemaSimpleContentExtension
operator|)
name|content
operator|.
name|getContent
argument_list|()
decl_stmt|;
if|if
condition|(
name|XmlSchemaConstants
operator|.
name|BASE64BINARY_QNAME
operator|.
name|equals
argument_list|(
name|extension
operator|.
name|getBaseTypeName
argument_list|()
argument_list|)
condition|)
block|{
return|return
literal|true
return|;
block|}
block|}
block|}
block|}
return|return
literal|false
return|;
block|}
comment|/**      * Given an element, generate the serialization code.      *       * @param elementInfo description of the element we are serializing      * @param referencePrefix prefix to the Javascript variable. Nothing for      *                args, this._ for members.      * @param schemaCollection caller's schema collection.      */
specifier|public
name|void
name|generateCodeToSerializeElement
parameter_list|(
name|ParticleInfo
name|elementInfo
parameter_list|,
name|String
name|referencePrefix
parameter_list|,
name|SchemaCollection
name|schemaCollection
parameter_list|)
block|{
name|XmlSchemaType
name|type
init|=
name|elementInfo
operator|.
name|getType
argument_list|()
decl_stmt|;
name|boolean
name|nillable
init|=
name|elementInfo
operator|.
name|isNillable
argument_list|()
decl_stmt|;
name|boolean
name|optional
init|=
name|elementInfo
operator|.
name|isOptional
argument_list|()
decl_stmt|;
name|boolean
name|array
init|=
name|elementInfo
operator|.
name|isArray
argument_list|()
decl_stmt|;
name|boolean
name|mtom
init|=
name|treatAsMtom
argument_list|(
name|elementInfo
operator|.
name|getParticle
argument_list|()
argument_list|)
decl_stmt|;
name|String
name|jsVar
init|=
name|referencePrefix
operator|+
name|elementInfo
operator|.
name|getJavascriptName
argument_list|()
decl_stmt|;
name|appendLine
argument_list|(
literal|"// block for local variables"
argument_list|)
expr_stmt|;
name|startBlock
argument_list|()
expr_stmt|;
comment|// allow local variables.
comment|// first question: optional?
if|if
condition|(
name|optional
condition|)
block|{
name|startIf
argument_list|(
name|jsVar
operator|+
literal|" != null"
argument_list|)
expr_stmt|;
block|}
comment|// nillable and optional would be very strange together.
comment|// and nillable in the array case applies to the elements.
if|if
condition|(
name|nillable
operator|&&
operator|!
name|array
condition|)
block|{
name|startIf
argument_list|(
name|jsVar
operator|+
literal|" == null"
argument_list|)
expr_stmt|;
name|appendString
argument_list|(
literal|"<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|" "
operator|+
name|XmlSchemaUtils
operator|.
name|XSI_NIL
operator|+
literal|"/>"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|array
condition|)
block|{
comment|// protected against null in arrays.
name|startIf
argument_list|(
name|jsVar
operator|+
literal|" != null"
argument_list|)
expr_stmt|;
name|startFor
argument_list|(
literal|"var ax = 0"
argument_list|,
literal|"ax< "
operator|+
name|jsVar
operator|+
literal|".length"
argument_list|,
literal|"ax ++"
argument_list|)
expr_stmt|;
name|jsVar
operator|=
name|jsVar
operator|+
literal|"[ax]"
expr_stmt|;
comment|// we need an extra level of 'nil' testing here. Or do we, depending
comment|// on the type structure?
comment|// Recode and fiddle appropriately.
name|startIf
argument_list|(
name|jsVar
operator|+
literal|" == null"
argument_list|)
expr_stmt|;
if|if
condition|(
name|nillable
condition|)
block|{
name|appendString
argument_list|(
literal|"<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|" "
operator|+
name|XmlSchemaUtils
operator|.
name|XSI_NIL
operator|+
literal|"/>"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|appendString
argument_list|(
literal|"<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|"/>"
argument_list|)
expr_stmt|;
block|}
name|appendElse
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|elementInfo
operator|.
name|isAnyType
argument_list|()
condition|)
block|{
name|serializeAnyTypeElement
argument_list|(
name|elementInfo
argument_list|,
name|jsVar
argument_list|)
expr_stmt|;
comment|// mtom can be turned on for the special complex type that is really a basic type with
comment|// a content-type attribute.
block|}
elseif|else
if|if
condition|(
operator|!
name|mtom
operator|&&
name|type
operator|instanceof
name|XmlSchemaComplexType
condition|)
block|{
comment|// it has a value
comment|// pass the extra null in the slot for the 'extra namespaces' needed
comment|// by 'any'.
name|appendExpression
argument_list|(
name|jsVar
operator|+
literal|".serialize(cxfjsutils, '"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|"', null)"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// simple type
name|appendString
argument_list|(
literal|"<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|">"
argument_list|)
expr_stmt|;
if|if
condition|(
name|mtom
condition|)
block|{
name|appendExpression
argument_list|(
literal|"cxfjsutils.packageMtom("
operator|+
name|jsVar
operator|+
literal|")"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|appendExpression
argument_list|(
literal|"cxfjsutils.escapeXmlEntities("
operator|+
name|jsVar
operator|+
literal|")"
argument_list|)
expr_stmt|;
block|}
name|appendString
argument_list|(
literal|"</"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|">"
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|array
condition|)
block|{
name|endBlock
argument_list|()
expr_stmt|;
comment|// for the extra level of nil checking, which might be
comment|// wrong.
name|endBlock
argument_list|()
expr_stmt|;
comment|// for the for loop.
name|endBlock
argument_list|()
expr_stmt|;
comment|// the null protection.
block|}
if|if
condition|(
name|nillable
operator|&&
operator|!
name|array
condition|)
block|{
name|endBlock
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|optional
condition|)
block|{
name|endBlock
argument_list|()
expr_stmt|;
block|}
name|endBlock
argument_list|()
expr_stmt|;
comment|// local variables
block|}
specifier|private
name|void
name|serializeAnyTypeElement
parameter_list|(
name|ParticleInfo
name|elementInfo
parameter_list|,
name|String
name|jsVar
parameter_list|)
block|{
comment|// name a variable for convenience.
name|appendLine
argument_list|(
literal|"var anyHolder = "
operator|+
name|jsVar
operator|+
literal|";"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anySerializer;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var typeAttr = '';"
argument_list|)
expr_stmt|;
comment|// we look in the global array for a serializer.
name|startIf
argument_list|(
literal|"anyHolder != null"
argument_list|)
expr_stmt|;
name|startIf
argument_list|(
literal|"!anyHolder.raw"
argument_list|)
expr_stmt|;
comment|// no serializer for raw.
comment|// In anyType, the QName is for the type, not an element.
name|appendLine
argument_list|(
literal|"anySerializer = "
operator|+
literal|"cxfjsutils.interfaceObject.globalElementSerializers[anyHolder.qname];"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
name|startIf
argument_list|(
literal|"anyHolder.xsiType"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var typePrefix = 'cxfjst"
operator|+
name|anyTypePrefixCounter
operator|+
literal|"';"
argument_list|)
expr_stmt|;
name|anyTypePrefixCounter
operator|++
expr_stmt|;
name|appendLine
argument_list|(
literal|"var typeAttr = 'xmlns:' + typePrefix + '=\\\''"
operator|+
literal|" + anyHolder.namespaceURI + '\\\'';"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"typeAttr = typeAttr + ' xsi:type=\\\'' + typePrefix + ':' "
operator|+
literal|"+ anyHolder.localName + '\\\'';"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
name|startIf
argument_list|(
literal|"anySerializer"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
name|jsVar
operator|+
literal|".serialize(cxfjsutils, '"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|"', typeAttr)"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
comment|// simple type or raw
name|appendExpression
argument_list|(
literal|"'<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|" ' + typeAttr + "
operator|+
literal|"'>'"
argument_list|)
expr_stmt|;
name|startIf
argument_list|(
literal|"!anyHolder.raw"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
literal|"cxfjsutils.escapeXmlEntities("
operator|+
name|jsVar
operator|+
literal|")"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
name|appendExpression
argument_list|(
literal|"anyHolder.xml"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
name|appendString
argument_list|(
literal|"</"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|">"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
comment|// nil (from null holder)
name|appendString
argument_list|(
literal|"<"
operator|+
name|elementInfo
operator|.
name|getXmlName
argument_list|()
operator|+
literal|" "
operator|+
name|XmlSchemaUtils
operator|.
name|XSI_NIL
operator|+
literal|"/>"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
block|}
comment|/**      * Generate code to serialize an xs:any. There is too much duplicate code      * with the element serializer; fix that some day.      *       * @param elementInfo      * @param schemaCollection      */
specifier|public
name|void
name|generateCodeToSerializeAny
parameter_list|(
name|ParticleInfo
name|itemInfo
parameter_list|,
name|String
name|prefix
parameter_list|,
name|SchemaCollection
name|schemaCollection
parameter_list|)
block|{
name|boolean
name|optional
init|=
name|XmlSchemaUtils
operator|.
name|isParticleOptional
argument_list|(
name|itemInfo
operator|.
name|getParticle
argument_list|()
argument_list|)
decl_stmt|;
name|boolean
name|array
init|=
name|XmlSchemaUtils
operator|.
name|isParticleArray
argument_list|(
name|itemInfo
operator|.
name|getParticle
argument_list|()
argument_list|)
decl_stmt|;
name|appendLine
argument_list|(
literal|"var anyHolder = this._"
operator|+
name|itemInfo
operator|.
name|getJavascriptName
argument_list|()
operator|+
literal|";"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anySerializer = null;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anyXmlTag = null;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anyXmlNsDef = null;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anyData = null;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"var anyStartTag;"
argument_list|)
expr_stmt|;
name|startIf
argument_list|(
literal|"anyHolder != null&& !anyHolder.raw"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anySerializer = "
operator|+
literal|"cxfjsutils.interfaceObject.globalElementSerializers[anyHolder.qname];"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyXmlTag = '"
operator|+
name|prefix
operator|+
literal|":' + anyHolder.localName;"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyXmlNsDef = 'xmlns:"
operator|+
name|prefix
operator|+
literal|"=\\'' + anyHolder.namespaceURI"
operator|+
literal|" + '\\'';"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyStartTag = '<' + anyXmlTag + ' ' + anyXmlNsDef + '>';"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyEndTag = '</' + anyXmlTag + '>';"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyEmptyTag = '<' + anyXmlTag + ' ' + anyXmlNsDef + '/>';"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"anyData = anyHolder.object;"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
name|startIf
argument_list|(
literal|"anyHolder != null&& anyHolder.raw"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
literal|"anyHolder.xml"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
comment|// first question: optional?
if|if
condition|(
name|optional
condition|)
block|{
name|startIf
argument_list|(
literal|"anyHolder != null&& anyData != null"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|startIf
argument_list|(
literal|"anyHolder == null || anyData == null"
argument_list|)
expr_stmt|;
name|appendLine
argument_list|(
literal|"throw 'null value for required any item';"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
block|}
name|String
name|varRef
init|=
literal|"anyData"
decl_stmt|;
if|if
condition|(
name|array
condition|)
block|{
name|startFor
argument_list|(
literal|"var ax = 0"
argument_list|,
literal|"ax< anyData.length"
argument_list|,
literal|"ax ++"
argument_list|)
expr_stmt|;
name|varRef
operator|=
literal|"anyData[ax]"
expr_stmt|;
comment|// we need an extra level of 'nil' testing here. Or do we, depending
comment|// on the type structure?
comment|// Recode and fiddle appropriately.
name|startIf
argument_list|(
name|varRef
operator|+
literal|" == null"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
literal|"anyEmptyTag"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
block|}
name|startIf
argument_list|(
literal|"anySerializer"
argument_list|)
expr_stmt|;
comment|// if no constructor, a simple type.
comment|// it has a value
name|appendExpression
argument_list|(
literal|"anySerializer.call("
operator|+
name|varRef
operator|+
literal|", cxfjsutils, anyXmlTag, anyXmlNsDef)"
argument_list|)
expr_stmt|;
name|appendElse
argument_list|()
expr_stmt|;
name|appendExpression
argument_list|(
literal|"anyStartTag"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
literal|"cxfjsutils.escapeXmlEntities("
operator|+
name|varRef
operator|+
literal|")"
argument_list|)
expr_stmt|;
name|appendExpression
argument_list|(
literal|"anyEndTag"
argument_list|)
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
if|if
condition|(
name|array
condition|)
block|{
name|endBlock
argument_list|()
expr_stmt|;
name|endBlock
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|optional
condition|)
block|{
name|endBlock
argument_list|()
expr_stmt|;
block|}
name|endBlock
argument_list|()
expr_stmt|;
comment|// for raw
block|}
block|}
end_class

end_unit

