begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|jaxrs
operator|.
name|impl
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|WebApplicationException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|ext
operator|.
name|MessageBodyWriter
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|ext
operator|.
name|WriterInterceptor
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|ws
operator|.
name|rs
operator|.
name|ext
operator|.
name|WriterInterceptorContext
import|;
end_import

begin_class
specifier|public
class|class
name|WriterInterceptorMBW
implements|implements
name|WriterInterceptor
block|{
specifier|private
name|MessageBodyWriter
argument_list|<
name|Object
argument_list|>
name|writer
decl_stmt|;
specifier|public
name|WriterInterceptorMBW
parameter_list|(
name|MessageBodyWriter
argument_list|<
name|Object
argument_list|>
name|writer
parameter_list|)
block|{
name|this
operator|.
name|writer
operator|=
name|writer
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|aroundWriteTo
parameter_list|(
name|WriterInterceptorContext
name|c
parameter_list|)
throws|throws
name|IOException
throws|,
name|WebApplicationException
block|{
name|writer
operator|.
name|writeTo
argument_list|(
name|c
operator|.
name|getEntity
argument_list|()
argument_list|,
name|c
operator|.
name|getType
argument_list|()
argument_list|,
name|c
operator|.
name|getGenericType
argument_list|()
argument_list|,
name|c
operator|.
name|getAnnotations
argument_list|()
argument_list|,
name|c
operator|.
name|getMediaType
argument_list|()
argument_list|,
name|c
operator|.
name|getHeaders
argument_list|()
argument_list|,
name|c
operator|.
name|getOutputStream
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

