begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|builder
operator|.
name|primitive
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|ByteArrayInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Element
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|Bus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|helpers
operator|.
name|DOMUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|AssertionBuilderRegistry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyAssertion
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|ws
operator|.
name|policy
operator|.
name|PolicyException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|neethi
operator|.
name|Policy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|easymock
operator|.
name|classextension
operator|.
name|EasyMock
import|;
end_import

begin_import
import|import
name|org
operator|.
name|easymock
operator|.
name|classextension
operator|.
name|IMocksControl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_comment
comment|/**  *   */
end_comment

begin_class
specifier|public
class|class
name|NestedPrimitiveAssertionBuilderTest
extends|extends
name|Assert
block|{
specifier|private
specifier|static
specifier|final
name|String
name|TEST_NAMESPACE
init|=
literal|"http://www.w3.org/2007/01/addressing/metadata"
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|QName
name|TEST_NAME1
init|=
operator|new
name|QName
argument_list|(
name|TEST_NAMESPACE
argument_list|,
literal|"Addressing"
argument_list|)
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|QName
name|TEST_NAME2
init|=
operator|new
name|QName
argument_list|(
name|TEST_NAMESPACE
argument_list|,
literal|"AnonymousResponses"
argument_list|)
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|QName
name|TEST_NAME3
init|=
operator|new
name|QName
argument_list|(
name|TEST_NAMESPACE
argument_list|,
literal|"NonAnonymousResponses"
argument_list|)
decl_stmt|;
specifier|private
name|NestedPrimitiveAssertionBuilder
name|npab
decl_stmt|;
specifier|private
name|IMocksControl
name|control
decl_stmt|;
specifier|private
name|PolicyBuilder
name|builder
decl_stmt|;
specifier|private
name|AssertionBuilderRegistry
name|reg
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|setUp
parameter_list|()
block|{
name|control
operator|=
name|EasyMock
operator|.
name|createNiceControl
argument_list|()
expr_stmt|;
name|npab
operator|=
operator|new
name|NestedPrimitiveAssertionBuilder
argument_list|()
expr_stmt|;
name|npab
operator|.
name|setKnownElements
argument_list|(
name|Collections
operator|.
name|singletonList
argument_list|(
name|TEST_NAME1
argument_list|)
argument_list|)
expr_stmt|;
name|builder
operator|=
name|control
operator|.
name|createMock
argument_list|(
name|PolicyBuilder
operator|.
name|class
argument_list|)
expr_stmt|;
name|npab
operator|.
name|setPolicyBuilder
argument_list|(
name|builder
argument_list|)
expr_stmt|;
name|reg
operator|=
name|control
operator|.
name|createMock
argument_list|(
name|AssertionBuilderRegistry
operator|.
name|class
argument_list|)
expr_stmt|;
name|npab
operator|.
name|setAssertionBuilderRegistry
argument_list|(
name|reg
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBuildFailOlderNs
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|data
init|=
literal|"<wsam:Addressing wsp:Optional=\"true\""
operator|+
literal|" xmlns:wsp=\"http://www.w3.org/2006/07/ws-policy\""
operator|+
literal|" xmlns:wsam=\"http://www.w3.org/2007/01/addressing/metadata\" />"
decl_stmt|;
try|try
block|{
name|npab
operator|.
name|build
argument_list|(
name|getElement
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"Expected PolicyException not thrown."
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|PolicyException
name|ex
parameter_list|)
block|{
comment|// expected
block|}
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBuildDefaultNs
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|data
init|=
literal|"<wsam:Addressing wsp:Optional=\"true\""
operator|+
literal|" xmlns:wsp=\"http://www.w3.org/ns/ws-policy\""
operator|+
literal|" xmlns:wsam=\"http://www.w3.org/2007/01/addressing/metadata\">"
operator|+
literal|"<wsp:Policy/></wsam:Addressing>"
decl_stmt|;
name|Policy
name|nested
init|=
name|control
operator|.
name|createMock
argument_list|(
name|Policy
operator|.
name|class
argument_list|)
decl_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|builder
operator|.
name|getPolicy
argument_list|(
name|EasyMock
operator|.
name|isA
argument_list|(
name|Element
operator|.
name|class
argument_list|)
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|nested
argument_list|)
expr_stmt|;
name|control
operator|.
name|replay
argument_list|()
expr_stmt|;
name|NestedPrimitiveAssertion
name|npc
init|=
operator|(
name|NestedPrimitiveAssertion
operator|)
name|npab
operator|.
name|build
argument_list|(
name|getElement
argument_list|(
name|data
argument_list|)
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|TEST_NAME1
argument_list|,
name|npc
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|nested
argument_list|,
name|npc
operator|.
name|getPolicy
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|npc
operator|.
name|isOptional
argument_list|()
argument_list|)
expr_stmt|;
name|control
operator|.
name|verify
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBuildOlderNs
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|data
init|=
literal|"<wsam:Addressing wsp:Optional=\"true\""
operator|+
literal|" xmlns:wsp=\"http://www.w3.org/2006/07/ws-policy\""
operator|+
literal|" xmlns:wsam=\"http://www.w3.org/2007/01/addressing/metadata\">"
operator|+
literal|"<wsp:Policy/></wsam:Addressing>"
decl_stmt|;
name|Policy
name|nested
init|=
name|control
operator|.
name|createMock
argument_list|(
name|Policy
operator|.
name|class
argument_list|)
decl_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|builder
operator|.
name|getPolicy
argument_list|(
name|EasyMock
operator|.
name|isA
argument_list|(
name|Element
operator|.
name|class
argument_list|)
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|nested
argument_list|)
expr_stmt|;
name|PolicyConstants
name|pc
init|=
operator|new
name|PolicyConstants
argument_list|()
decl_stmt|;
name|pc
operator|.
name|setNamespace
argument_list|(
name|PolicyConstants
operator|.
name|NAMESPACE_W3_200607
argument_list|)
expr_stmt|;
name|Bus
name|bus
init|=
name|control
operator|.
name|createMock
argument_list|(
name|Bus
operator|.
name|class
argument_list|)
decl_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|bus
operator|.
name|getExtension
argument_list|(
name|PolicyConstants
operator|.
name|class
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|pc
argument_list|)
expr_stmt|;
name|control
operator|.
name|replay
argument_list|()
expr_stmt|;
name|npab
operator|.
name|setBus
argument_list|(
name|bus
argument_list|)
expr_stmt|;
name|NestedPrimitiveAssertion
name|npc
init|=
operator|(
name|NestedPrimitiveAssertion
operator|)
name|npab
operator|.
name|build
argument_list|(
name|getElement
argument_list|(
name|data
argument_list|)
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|TEST_NAME1
argument_list|,
name|npc
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|nested
argument_list|,
name|npc
operator|.
name|getPolicy
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|npc
operator|.
name|isOptional
argument_list|()
argument_list|)
expr_stmt|;
name|control
operator|.
name|verify
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBuildCompatibleNoRegistry
parameter_list|()
block|{
name|npab
operator|.
name|setAssertionBuilderRegistry
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|Policy
index|[]
name|policies
init|=
name|NestedPrimitiveAssertionTest
operator|.
name|buildTestPolicies
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|a
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
literal|4
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|assertNull
argument_list|(
literal|"Should not have been able to build compatible policy."
argument_list|,
name|npab
operator|.
name|buildCompatible
argument_list|(
name|a
argument_list|,
name|a
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testCompatibleWithSelf
parameter_list|()
block|{
name|Policy
index|[]
name|policies
init|=
name|NestedPrimitiveAssertionTest
operator|.
name|buildTestPolicies
argument_list|()
decl_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME1
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|npab
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|PrimitiveAssertionBuilder
name|ab1
init|=
operator|new
name|PrimitiveAssertionBuilder
argument_list|()
decl_stmt|;
name|ab1
operator|.
name|setKnownElements
argument_list|(
name|Collections
operator|.
name|singleton
argument_list|(
name|TEST_NAME2
argument_list|)
argument_list|)
expr_stmt|;
name|PrimitiveAssertionBuilder
name|ab2
init|=
operator|new
name|PrimitiveAssertionBuilder
argument_list|()
decl_stmt|;
name|ab2
operator|.
name|setKnownElements
argument_list|(
name|Collections
operator|.
name|singleton
argument_list|(
name|TEST_NAME3
argument_list|)
argument_list|)
expr_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME2
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|ab1
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME3
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|ab2
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|control
operator|.
name|replay
argument_list|()
expr_stmt|;
name|PolicyAssertion
name|a
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
literal|2
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|compatible
init|=
name|npab
operator|.
name|buildCompatible
argument_list|(
name|a
argument_list|,
name|a
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"assertion in policy 2 should be compatible with itself."
argument_list|,
name|compatible
argument_list|)
expr_stmt|;
name|control
operator|.
name|verify
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testBuildCompatible
parameter_list|()
block|{
name|Policy
index|[]
name|policies
init|=
name|NestedPrimitiveAssertionTest
operator|.
name|buildTestPolicies
argument_list|()
decl_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME1
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|npab
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|PrimitiveAssertionBuilder
name|ab1
init|=
operator|new
name|PrimitiveAssertionBuilder
argument_list|()
decl_stmt|;
name|ab1
operator|.
name|setKnownElements
argument_list|(
name|Collections
operator|.
name|singleton
argument_list|(
name|TEST_NAME2
argument_list|)
argument_list|)
expr_stmt|;
name|PrimitiveAssertionBuilder
name|ab2
init|=
operator|new
name|PrimitiveAssertionBuilder
argument_list|()
decl_stmt|;
name|ab2
operator|.
name|setKnownElements
argument_list|(
name|Collections
operator|.
name|singleton
argument_list|(
name|TEST_NAME3
argument_list|)
argument_list|)
expr_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME2
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|ab1
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|EasyMock
operator|.
name|expect
argument_list|(
name|reg
operator|.
name|get
argument_list|(
name|TEST_NAME3
argument_list|)
argument_list|)
operator|.
name|andReturn
argument_list|(
name|ab2
argument_list|)
operator|.
name|anyTimes
argument_list|()
expr_stmt|;
name|control
operator|.
name|replay
argument_list|()
expr_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|policies
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|PolicyAssertion
name|a
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
name|i
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|compatible
init|=
name|npab
operator|.
name|buildCompatible
argument_list|(
name|a
argument_list|,
name|a
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"assertion in policy "
operator|+
name|i
operator|+
literal|" should be compatible with itself."
argument_list|,
name|compatible
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|int
name|i
init|=
literal|1
init|;
name|i
operator|<
literal|5
condition|;
name|i
operator|++
control|)
block|{
name|PolicyAssertion
name|a
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
literal|0
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|b
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
name|i
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|compatible
init|=
name|npab
operator|.
name|buildCompatible
argument_list|(
name|a
argument_list|,
name|b
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"assertion in policy 0 should be compatible with assertion in policy "
operator|+
name|i
operator|+
literal|"."
argument_list|,
name|compatible
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|int
name|i
init|=
literal|2
init|;
name|i
operator|<
literal|5
condition|;
name|i
operator|++
control|)
block|{
name|PolicyAssertion
name|a
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
literal|1
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|b
init|=
operator|(
name|PolicyAssertion
operator|)
name|policies
index|[
name|i
index|]
operator|.
name|getFirstPolicyComponent
argument_list|()
decl_stmt|;
name|PolicyAssertion
name|compatible
init|=
name|npab
operator|.
name|buildCompatible
argument_list|(
name|a
argument_list|,
name|b
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
literal|"assertion in policy "
operator|+
literal|1
operator|+
literal|" should be compatible with assertion in policy i."
argument_list|,
name|compatible
argument_list|)
expr_stmt|;
block|}
name|control
operator|.
name|verify
argument_list|()
expr_stmt|;
block|}
name|Element
name|getElement
parameter_list|(
name|String
name|data
parameter_list|)
throws|throws
name|Exception
block|{
name|InputStream
name|is
init|=
operator|new
name|ByteArrayInputStream
argument_list|(
name|data
operator|.
name|getBytes
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|DOMUtils
operator|.
name|readXml
argument_list|(
name|is
argument_list|)
operator|.
name|getDocumentElement
argument_list|()
return|;
block|}
block|}
end_class

end_unit

