begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|systest
operator|.
name|mtom
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|activation
operator|.
name|DataHandler
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlMimeType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_class
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|"Data"
argument_list|,
name|namespace
operator|=
literal|"http://mtom.systest.cxf.apache.org"
argument_list|)
annotation|@
name|XmlAccessorType
argument_list|(
name|XmlAccessType
operator|.
name|FIELD
argument_list|)
specifier|public
class|class
name|Data
block|{
annotation|@
name|XmlElement
argument_list|(
name|name
operator|=
literal|"someData"
argument_list|,
name|namespace
operator|=
literal|"http://mtom.systest.cxf.apache.org"
argument_list|)
annotation|@
name|XmlMimeType
argument_list|(
literal|"application/octet-stream"
argument_list|)
specifier|protected
name|DataHandler
name|someData
decl_stmt|;
specifier|public
name|DataHandler
name|getSomeData
parameter_list|()
block|{
return|return
name|someData
return|;
block|}
specifier|public
name|void
name|setSomeData
parameter_list|(
name|DataHandler
name|someData
parameter_list|)
block|{
name|this
operator|.
name|someData
operator|=
name|someData
expr_stmt|;
block|}
block|}
end_class

end_unit

