begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|http
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|Bus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|endpoint
operator|.
name|Client
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|feature
operator|.
name|AbstractPortableFeature
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|feature
operator|.
name|DelegatingFeature
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|transport
operator|.
name|Conduit
import|;
end_import

begin_comment
comment|/**  * Programmatically configure a http conduit. This can also be used as a DOSGi  * intent.  */
end_comment

begin_class
specifier|public
class|class
name|HttpConduitFeature
extends|extends
name|DelegatingFeature
argument_list|<
name|HttpConduitFeature
operator|.
name|Portable
argument_list|>
block|{
specifier|public
name|HttpConduitFeature
parameter_list|()
block|{
name|super
argument_list|(
operator|new
name|Portable
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setConduitConfig
parameter_list|(
name|HttpConduitConfig
name|conduitConfig
parameter_list|)
block|{
name|delegate
operator|.
name|setConduitConfig
argument_list|(
name|conduitConfig
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
class|class
name|Portable
implements|implements
name|AbstractPortableFeature
block|{
specifier|private
name|HttpConduitConfig
name|conduitConfig
decl_stmt|;
annotation|@
name|Override
specifier|public
name|void
name|initialize
parameter_list|(
name|Client
name|client
parameter_list|,
name|Bus
name|bus
parameter_list|)
block|{
name|Conduit
name|conduit
init|=
name|client
operator|.
name|getConduit
argument_list|()
decl_stmt|;
if|if
condition|(
name|conduitConfig
operator|!=
literal|null
operator|&&
name|conduit
operator|instanceof
name|HTTPConduit
condition|)
block|{
name|conduitConfig
operator|.
name|apply
argument_list|(
operator|(
name|HTTPConduit
operator|)
name|conduit
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|setConduitConfig
parameter_list|(
name|HttpConduitConfig
name|conduitConfig
parameter_list|)
block|{
name|this
operator|.
name|conduitConfig
operator|=
name|conduitConfig
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

