begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements. See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership. The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied. See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cxf
operator|.
name|tools
operator|.
name|corba
operator|.
name|idlpreprocessor
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStreamReader
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|LineNumberReader
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URL
import|;
end_import

begin_comment
comment|/**  * Provides information about a file that  */
end_comment

begin_class
class|class
name|IncludeStackEntry
block|{
specifier|private
specifier|final
name|URL
name|url
decl_stmt|;
specifier|private
name|LineNumberReader
name|reader
decl_stmt|;
specifier|private
specifier|final
name|String
name|location
decl_stmt|;
name|IncludeStackEntry
parameter_list|(
name|URL
name|link
parameter_list|,
name|String
name|loc
parameter_list|)
throws|throws
name|IOException
block|{
name|this
operator|.
name|url
operator|=
name|link
expr_stmt|;
name|this
operator|.
name|location
operator|=
name|loc
expr_stmt|;
name|this
operator|.
name|reader
operator|=
operator|new
name|LineNumberReader
argument_list|(
operator|new
name|InputStreamReader
argument_list|(
name|url
operator|.
name|openStream
argument_list|()
argument_list|,
literal|"ISO-8859-1"
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|reader
operator|.
name|setLineNumber
argument_list|(
literal|1
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getLocation
parameter_list|()
block|{
return|return
name|location
return|;
block|}
specifier|public
name|URL
name|getURL
parameter_list|()
block|{
return|return
name|url
return|;
block|}
specifier|public
name|LineNumberReader
name|getReader
parameter_list|()
block|{
return|return
name|reader
return|;
block|}
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"IncludeStackEntry[url="
operator|+
name|url
operator|+
literal|", location="
operator|+
name|location
operator|+
literal|", line="
operator|+
name|reader
operator|.
name|getLineNumber
argument_list|()
operator|+
literal|"]"
return|;
block|}
block|}
end_class

end_unit

